// GENERATED by scripts/generate_aria_safety_swift.py from
// backend/infra/lambda/aria_core/guidance.py. Do not edit by hand:
// change guidance.py, then run the script. CI runs it with --check.

import Foundation

/// Needles, patterns, and copy for `AriaSafetyTriage` — the same words
/// the backend's one safety classifier uses.
enum AriaSafetyLexicon {

    // MARK: Needles (substring, lowercased input)

    static let selfHarm: [String] = [
        "suicidal",
        "kill myself",
        "want to die",
        "end my life",
        "take my own life",
        "don't want to be here",
        "dont want to be here",
        "don't want to live",
        "dont want to live",
        "do not want to live",
        "don't want to be alive",
        "dont want to be alive",
        "end it all",
        "ending it all",
        "thinking about ending it",
        "thinking of ending it",
        "better off dead",
        "better off without me",
        "no reason to live",
        "nothing to live for",
        "nobody would miss me",
        "no one would miss me",
        "wish i was dead",
        "wish i were dead",
        "thinking about suicide",
        "thinking of suicide",
        "commit suicide",
        "harm myself",
        "harming myself",
        "self harm",
        "self-harm",
    ]

    static let escalationRequest: [String] = [
        "call 911",
        "call 9-1-1",
        "dial 911",
        "call emergency",
        "call an ambulance",
        "call the ambulance",
        "get an ambulance",
        "emergency sos",
        "call for help",
    ]

    static let emergencyState: [String] = [
        "not breathing",
        "isn't breathing",
        "isnt breathing",
        "stopped breathing",
        "won't wake up",
        "wont wake up",
        "unresponsive",
        "no pulse",
        "no heartbeat",
        "collapsed",
        "passed out",
        "unconscious",
        "having a heart attack",
        "heart attack",
        "having a stroke",
        "face is drooping",
        "overdosed",
        "overdosing",
        "overdose",
        "bleeding out",
        "won't stop bleeding",
        "wont stop bleeding",
        "gushing blood",
        "drowning",
        "not responding",
        "turning blue",
        "seizure",
        "convulsing",
        "anaphylaxis",
        "anaphylactic",
        "throat is closing",
        "can't breathe",
        "cant breathe",
        "cannot breathe",
    ]

    static let chestMarkers: [String] = [
        "chest pain",
        "chest pressure",
        "chest tightness",
        "chest feels tight",
        "chest is tight",
        "chest hurt",
        "chest hurts",
        "pain in my chest",
        "pain in the chest",
        "pressure in my chest",
        "pressure in the chest",
        "tightness in my chest",
        "my chest hurts",
        "my chest hurt",
    ]

    static let severeChest: [String] = [
        "crushing chest pressure",
        "crushing chest pain",
        "crushing pressure in my chest",
        "crushing pain in my chest",
    ]

    static let chestCompanions: [String] = [
        "arm is numb",
        "arm numb",
        "numb arm",
        "numbness in my arm",
        "numbness in the arm",
        "arm hurts",
        "arm pain",
        "pain in my arm",
        "pain in the arm",
        "left arm",
        "right arm",
        "jaw ache",
        "jaw aches",
        "jaw pain",
        "jaw hurts",
        "jaw hurt",
        "ache in my jaw",
        "back pain",
        "pain in my back",
        "shortness of breath",
        "short of breath",
        "can't breathe",
        "cant breathe",
        "cannot breathe",
        "hard to breathe",
        "difficulty breathing",
        "cold sweat",
        "cold sweats",
        "clammy",
    ]

    static let strokeStandalone: [String] = [
        "face is drooping",
        "face drooping",
        "drooping face",
        "face droops",
        "face is droopy",
        "face feels droopy",
        "slurred speech",
        "speech is slurred",
        "words are slurred",
        "slurring my words",
        "slurring words",
        "slurring his words",
        "slurring her words",
        "slurring their words",
        "sudden confusion",
        "suddenly confused",
        "worst headache",
        "smile is crooked",
        "crooked smile",
        "smile is lopsided",
        "lopsided smile",
        "face is lopsided",
        "face looks lopsided",
        "face is sagging",
        "can't see out of one eye",
        "cant see out of one eye",
        "lost vision in one eye",
        "lost the vision in one eye",
        "sudden vision loss",
        "suddenly can't see",
        "suddenly cant see",
        "suddenly blind",
        "went blind",
        "suddenly seeing double",
        "sudden double vision",
        "words are coming out wrong",
        "words are coming out jumbled",
        "words are jumbled",
        "speech is garbled",
        "garbled speech",
        "can't get my words out",
        "cant get my words out",
        "suddenly can't speak",
        "suddenly cant speak",
        "suddenly can't talk",
        "suddenly cant talk",
    ]

    static let liftChestContext: [String] = [
        "after bench",
        "after chest day",
        "after lifting",
        "after press",
        "after workout",
        "after training",
        "after push",
        "from bench",
        "from chest day",
        "from lifting",
        "chest day",
    ]

    static let liftSoreness: [String] = [
        "sore",
        "tight",
        "tightness",
    ]

    static let liftNotSoreness: [String] = [
        "pain",
        "hurt",
        "hurts",
        "pressure",
        "crushing",
    ]

    static let syncopeStandalone: [String] = [
        "fainted",
        "fainting",
        "blacked out",
        "blacking out",
        "passed out",
    ]

    static let notBreathing: [String] = [
        "not breathing",
        "isn't breathing",
        "isnt breathing",
        "stopped breathing",
    ]

    static let unresponsive: [String] = [
        "unresponsive",
        "won't wake up",
        "wont wake up",
        "unconscious",
        "not responding",
        "isn't waking up",
        "isnt waking up",
        "can't wake him",
        "cant wake him",
        "can't wake her",
        "cant wake her",
        "can't wake them",
        "cant wake them",
    ]

    static let noCirculation: [String] = [
        "no pulse",
        "no heartbeat",
    ]

    static let allergyEmergency: [String] = [
        "throat is swelling",
        "throat's swelling",
        "throat swelling",
        "throat is closing",
        "throat's closing",
        "swelling in my throat",
        "tongue is swelling",
        "tongue swelling",
        "anaphylaxis",
        "anaphylactic",
        "used my epipen",
        "use my epipen",
        "used an epipen",
        "need my epipen",
        "used her epipen",
        "used his epipen",
        "need an epipen",
    ]

    static let howtoCues: [String] = [
        "how do i",
        "how to",
        "how can i",
        "what do i do",
        "what should i do",
        "steps to",
        "how would i",
        "teach me",
        "walk me through",
        "show me how",
    ]

    static let firstAidTopics: [String] = [
        "cpr",
        "rescue breath",
        "heimlich",
        "choking",
        "aed",
        "defibrillator",
        "defibrillate",
        "recovery position",
        "stop the bleeding",
        "stop bleeding",
        "bleeding",
        "tourniquet",
        "first aid",
        "first-aid",
        "someone is choking",
        "someone collapsed",
        "someone passed out",
        "burn",
        "burns",
        "scald",
        "scalded",
        "drowning",
        "seizure",
        "nosebleed",
    ]

    static let directDiagnosis: [String] = [
        "diagnose",
        "diagnosis",
        "what's wrong with me",
        "whats wrong with me",
        "what is wrong with me",
        "what do i have",
        "am i sick",
        "is something wrong with me",
        "what disease",
        "what condition do i have",
    ]

    static let diagnosisAsk: [String] = [
        "do i have",
        "could i have",
        "might i have",
        "do you think i have",
        "is this ",
        "is it ",
        "am i having a",
    ]

    static let conditionTerms: [String] = [
        "cancer",
        "tumor",
        "diabetes",
        "diabetic",
        "covid",
        "the flu",
        "infection",
        "infected",
        "disease",
        "disorder",
        "concussion",
        "fracture",
        "fractured",
        "broken bone",
        "torn",
        "ruptured",
        "herniated",
        "pneumonia",
        "asthma",
        "arthritis",
        "depression",
        "anxiety disorder",
        "adhd",
        "std",
        "sti",
        "uti",
        "hypertension",
        "thyroid",
        "anemia",
        "ulcer",
        "appendicitis",
        "blood clot",
        "dvt",
        "hernia",
        "kidney stone",
        "gallstone",
        "sepsis",
        "meningitis",
        "sleep apnea",
        "sleep apnoea",
        "apnea",
        "apnoea",
    ]

    static let directMed: [String] = [
        "prescribe",
        "prescription for",
        "what medication",
        "which medication",
        "what medicine",
        "what drug",
        "my medication",
        "my meds",
        "my dose",
        "my dosage",
        "increase my dose",
        "decrease my dose",
        "up my dose",
        "lower my dose",
        "adjust my dose",
        "double my dose",
        "change my dose",
        "stop taking",
        "should i stop my",
        "off my meds",
        "how much insulin",
        "what dosage",
        "what dose",
        "how many mg",
        "mg of",
    ]

    static let takeCues: [String] = [
        "what should i take",
        "what can i take",
        "should i take",
        "can i take",
    ]

    static let symptomTerms: [String] = [
        "pain",
        "headache",
        "migraine",
        "fever",
        "cough",
        "cold",
        "flu",
        "nausea",
        "vomiting",
        "diarrhea",
        "rash",
        "cramps",
        "ache",
        "sore throat",
        "infection",
        "dizzy",
        "dizziness",
        "chest",
    ]

    static let medTerms: [String] = [
        "ibuprofen",
        "tylenol",
        "aspirin",
        "advil",
        "acetaminophen",
        "paracetamol",
        "insulin",
        "medication",
        "medicine",
        "meds",
        "pill",
        "tablet",
        "drug",
        "prescription",
        "antibiotic",
    ]

    static let eatingDisorder: [String] = [
        "make myself throw up",
        "make myself puke",
        "make myself sick after",
        "make myself vomit",
        "throw up after eating",
        "throw up after meals",
        "throw up after dinner",
        "purge after",
        "purging after",
        "how little can i eat",
        "how little should i eat",
        "stop eating for",
        "not eat for days",
        "starve myself",
        "starving myself",
        "skip eating for days",
        "eat nothing for",
        "laxatives to lose",
    ]

    static let helperPerson: [String] = [
        "my dad",
        "my mom",
        "my mum",
        "my father",
        "my mother",
        "my friend",
        "my wife",
        "my husband",
        "my partner",
        "my brother",
        "my sister",
        "my girlfriend",
        "my boyfriend",
        "my son",
        "my daughter",
        "someone",
        "my kid",
        "my child",
        "my baby",
        "my toddler",
        "my grandma",
        "my grandpa",
        "my grandmother",
        "my grandfather",
        "my roommate",
        "my coworker",
        "my teammate",
        "my buddy",
        "my aunt",
        "my uncle",
        "my cousin",
        "my neighbor",
        "my neighbour",
        "my fiance",
        "my fiancé",
        "my spouse",
        "my client",
    ]

    static let sleepRefer: [String] = [
        "sleep apnea",
        "sleep apnoea",
        "apnea",
        "apnoea",
        "insomnia",
        "sleep",
    ]

    static let youngChildCues: [String] = [
        "baby",
        "toddler",
        "infant",
        "little one",
    ]

    static let faintCues: [String] = [
        "feel faint",
        "feels faint",
        "feeling faint",
        "felt faint",
        "going to pass out",
        "gonna pass out",
        "about to pass out",
        "might pass out",
        "going to faint",
        "gonna faint",
        "about to faint",
        "lightheaded",
        "light-headed",
        "light headed",
        "dizzy",
        "dizziness",
        "room is spinning",
        "room's spinning",
        "vision is going grey",
        "vision is going gray",
        "vision went grey",
        "vision went gray",
    ]

    static let chestCleared: [String] = [
        "doctor said",
        "doctor cleared",
        "doc said",
        "doc cleared",
        "cardiologist said",
        "cardiologist cleared",
        "got it checked",
        "had it checked",
        "was checked out",
        "got checked out",
        "ruled out",
        "ecg was",
        "ekg was",
        "ecg came back",
        "ekg came back",
        "tests came back",
        "cleared me",
    ]

    static let chestMskCues: [String] = [
        "when i press",
        "when i push on",
        "when i touch",
        "press on it",
        "push on it",
        "touch it",
        "sore",
        "tender",
        "when i move",
        "when i twist",
        "when i stretch",
        "after chest day",
        "after bench",
        "pulled",
        "strained",
        "muscle",
    ]

    static let recurringCues: [String] = [
        "again",
        "keeps happening",
        "keep happening",
        "every time",
        "a lot lately",
        "for days",
        "for weeks",
        "all week",
        "third time",
        "second time",
        "happens often",
        "happens a lot",
        "keeps coming back",
    ]

    static let woundNeedsLookCues: [String] = [
        "deep",
        "gaping",
        "wide open",
        "stitches",
        "can see",
        "bone",
        "rusty",
        "dirty",
        "bite",
        "bit me",
        "bit him",
        "bit her",
        "glass",
        "face",
        "eye",
    ]

    static let negators: [String] = [
        "aren't",
        "arent",
        "didn't",
        "didnt",
        "doesn't",
        "doesnt",
        "don't",
        "dont",
        "isn't",
        "isnt",
        "neither",
        "never",
        "no",
        "none",
        "nor",
        "not",
        "nothing",
        "without",
    ]

    static let seizureWords: [String] = [
        "seizure",
        "convulsing",
    ]

    static let overdoseWords: [String] = [
        "overdosed",
        "overdosing",
        "overdose",
    ]

    static let heartAttack: [String] = [
        "heart attack",
    ]

    static let havingAStroke: [String] = [
        "having a stroke",
    ]

    static let jawWord: [String] = [
        "jaw",
    ]

    static let jawPain: [String] = [
        "ache",
        "aches",
        "aching",
        "pain",
        "hurt",
        "hurts",
        "numb",
    ]

    static let firstAidBurnWords: [String] = [
        "burn",
        "burns",
        "scald",
        "scalded",
        "scalds",
    ]

    static let triageTopics: [String] = [
        "chest_pain",
        "faint",
        "ingestion",
        "bleeding",
    ]

    /// Smart punctuation folded to the straight form every needle uses.
    static let quoteFolds: [String: String] = [
        "’": "'",
        "‘": "'",
        "ʼ": "'",
        "`": "'",
        "“": "\"",
        "”": "\"",
    ]

    // MARK: Patterns (NSRegularExpression, lowercased input)

    static let selfHarmPattern = #"\bcutting myself\b(?!\s+(?:some\s+)?(?:slack|off|short|a break|out|loose))|\bcut myself\b(?=[^.?!]{0,20}\b(?:on purpose|again|to feel)\b)"#
    static let hurtSelfPattern = #"\bhurt(?:ing)? myself\b"#
    static let hurtSelfInjuryPattern = #"\bhurt(?:ing)? myself\s+(?:at|in|on|during|while|doing|when|lifting|deadlifting|squatting|benching|running|playing|training|skiing|climbing|falling|stretching|moving|with)\b|\b(?:deadlift\w*|squat\w*|bench\w*|lifting|gym|workout|training|practice|game|match|run|ride|hike)\b[^.?!]{0,40}\bhurt(?:ing)? myself\b"#
    static let cantTalkRightPattern = #"\bcan(?:not|'?t) talk right(?! now)\b"#
    static let oneSidedDeficitPattern = #"\b(?:one|left|right) side\b.{0,40}\b(?:weak|weaker|numb|numbness)\b|\b(?:weak|weaker|numb|numbness)\b.{0,40}\b(?:one|left|right) side\b"#
    static let allergyComboPattern = #"\b(?:allergic reaction|allergy attack|reacting to)\b[^.?!]{0,60}\b(?:throat|tongue|lips|face|swell\w*|breath\w*|wheez\w*|hives all over)\b|\b(?:lips|face|tongue)\b[^.?!]{0,20}\bswell\w*\b[^.?!]{0,40}\b(?:breath\w*|wheez\w*|throat)\b"#
    static let bleedingPattern = #"\bbleeding\b[^.?!]{0,30}\b(?:won'?t|will not|doesn'?t|does not|isn'?t|not|can'?t)\s+(?:stop|stopping|slow|slowing)\b|\bblood (?:is )?(?:pouring|gushing|spurting|squirting)\b|\b(?:spurting|gushing|pouring) blood\b|\bbleeding out\b|\bwon'?t stop bleeding\b|\bcan'?t stop the bleeding\b"#
    static let bleedingTriagePattern = #"\bbleeding (?:a lot|heavily|badly|really bad|so much|like crazy|everywhere)\b|\b(?:so much|a lot of|lots of|losing(?: a lot of)?) blood\b|\bblood everywhere\b"#
    static let chokingPattern = #"\b(?:is|he's|hes|she's|shes|they're|theyre|i'm|im|am|are|keeps|started|kid's|baby's|son's|daughter's)\s+choking\b(?!\s+(?:under|up|in the|in games|in big|in every|at the|on (?:my|his|her|their) words|on the (?:free throw|putt|serve|penalty)))|\bchoking on (?:a|an|some|food|something|his|her|their|my|the)\b(?!\s+(?:words|free throw|putt|serve|penalty|lead|game))"#
    static let headInjuryPattern = #"\b(?:hit|banged|smacked|bumped|knocked|whacked|slammed) (?:my|his|her|their) head\b|\bhead injury\b|\bfell (?:and|on) (?:hit|landed on) (?:my|his|her|their) head\b|\bhit in the head\b"#
    static let headInjuryRedFlagPattern = #"\b(?:throw(?:ing)? up|threw up|vomit\w*|puking|puked|confused|confusion|passed out|blacked out|knocked out|unconscious|seizure|can'?t remember|worst headache|headache (?:is )?getting worse|slurr\w*|very sleepy|drowsy|can'?t stay awake|won'?t wake|clear fluid|one pupil)\b"#
    static let ingestionMedPattern = #"\b(?:took|taken|swallowed|ate|eaten|drank|drunk|had|popped|downed|ingested|chugged|got into)\b[^.?!]{0,30}\b(?:too many|too much|a bunch of|a handful of|handfuls of|a (?:whole|full|entire) (?:bottle|pack|packet|box|sheet)(?: of)?|the (?:whole|entire) (?:bottle|pack|packet|box)(?: of)?|double (?:my|his|her|their|the))\b[^.?!]{0,25}\b(?:pills?|meds|medicine|medications?|tablets?|capsules?|tylenol|advil|motrin|aleve|ibuprofen|acetaminophen|paracetamol|painkillers?|insulin|sleeping pills|sleep aids?|caffeine pills|xanax|adderall|oxy\w*|opioids?|fentanyl|benadryl|doses?|dosage)\b"#
    static let ingestionToxinPattern = #"\b(?:took|taken|swallowed|ate|eaten|drank|drunk|had|popped|downed|ingested|chugged|got into)\b[^.?!]{0,30}\b(?:bleach|detergent|laundry pods?|tide pods?|button batter(?:y|ies)|batter(?:y|ies)|drain cleaner|oven cleaner|cleaning (?:spray|product|fluid)|antifreeze|rat poison|pesticide|weed killer|lighter fluid|gasoline|lamp oil|nail polish remover|windshield (?:washer )?fluid|poison(?:ous)? (?:mushrooms?|berries|plants?))\b"#
    static let childIngestionPattern = #"\b(?:kid|son|daughter|baby|toddler|child|little one)\b[^.?!]{0,30}\b(?:took|taken|swallowed|ate|eaten|drank|drunk|had|popped|downed|ingested|chugged|got into)\b[^.?!]{0,25}\b(?:(?:pills?|meds|medicine|medications?|tablets?|capsules?|tylenol|advil|motrin|aleve|ibuprofen|acetaminophen|paracetamol|painkillers?|insulin|sleeping pills|sleep aids?|caffeine pills|xanax|adderall|oxy\w*|opioids?|fentanyl|benadryl|doses?|dosage)|(?:bleach|detergent|laundry pods?|tide pods?|button batter(?:y|ies)|batter(?:y|ies)|drain cleaner|oven cleaner|cleaning (?:spray|product|fluid)|antifreeze|rat poison|pesticide|weed killer|lighter fluid|gasoline|lamp oil|nail polish remover|windshield (?:washer )?fluid|poison(?:ous)? (?:mushrooms?|berries|plants?)))\b"#
    static let poisonedPattern = #"\b(?:been|was|got|i'?m|im|am|is|he's|she's)\s+poisoned\b|\bpoisoned (?:myself|himself|herself|themselves)\b|\bod'?d\b"#
    static let ingestionIntentPattern = #"\bon purpose\b|\bdeliberately\b|\bintentionally\b|\bmeant to\b|\bto (?:die|end it|end my life|hurt myself|kill myself)\b"#
    static let ingestionDangerPattern = #"\b(?:drowsy|can'?t stay awake|hard to wake|won'?t wake|barely awake|passing out|confused|seizure|seizing|shaking all over|turning blue|blue lips|throwing up blood|vomiting blood|barely breathing|breathing (?:slow|slowly|weird|funny|shallow))\b"#
    static let helperPronounPattern = #"\b(?:(?:her|his|their)\s+(?:face|arm|chest|jaw|head|speech|side|body|words?|pulse)|(?:he|she|they|he's|she's|they're|hes|shes|theyre)\s+(?:not\s+)?(?:breathing|collapsed|fainted|fainting|overdosed|blacked|passed|having|has|have|had|is|are|isn't|isnt|unresponsive|suddenly|took|swallowed|drank|ate|feels|seems|looks|keeps|choking|can't|cant|won't|wont|can\s+not))\b"#
    static let firstPersonPattern = #"\b(i|i'm|i've|me|my)\b"#
    static let yesLeadPattern = #"^\s*(?:yes|yeah|yea|yep|yup|ya|y|sure|i think so|kind of|kinda|sort of|a little|a bit|maybe|possibly|definitely|absolutely|it is|it does)\b"#
    static let noLeadPattern = #"^\s*(?:no|nope|nah|n|not really|none|neither|nothing like that|i'?m fine|im fine|i'?m okay|im okay|i'?m ok|im ok|all good|not at all|they'?re fine|they'?re okay|he'?s fine|she'?s fine|he'?s okay|she'?s okay)\b"#
    static let clauseBreakPattern = #"[,.;!?]|\b(?:but|though|although|except|however|yet)\b"#
    static let triageCardiacCuePattern = #"\b(?:chest|pound\w*|racing|(?:trouble|hard|difficult|difficulty|struggling)\s+(?:to\s+)?breath\w*|can'?t breathe|cannot breathe|short(?:ness)? of breath|breathless|out of breath)\b"#
    static let triageIntentCuePattern = #"\b(?:on purpose|hurt (?:myself|themselves|himself|herself)|wanted to|meant to|intentional\w*|deliberately|to die|end it)\b"#

    static let strokeDomainPatterns: [String] = [
        #"\b(?:face|smile)\b[^.?!]{0,25}\b(?:droop\w*|numb\w*|crooked|lopsided|uneven|sagging|won'?t move|feels? weird|feels? off)\b"#,
        #"\b(?:arm|leg|hand)\b[^.?!]{0,25}\b(?:weak\w*|numb\w*|dead|heavy|won'?t move|can'?t move|tingl\w*)\b|\bcan'?t (?:lift|move|feel|raise) (?:my|his|her|their) (?:left |right )?(?:arm|leg|hand)\b"#,
        #"\b(?:speech|words?|talking|voice)\b[^.?!]{0,25}\b(?:slurr\w*|weird|garbled|jumbled|wrong|funny|strange|off)\b|\bcan'?t (?:talk|speak) (?:right|properly|clearly)\b(?! now)"#,
        #"\b(?:can'?t see|lost (?:the )?vision|vision (?:went|is going|is) (?:black|dark|blurry|weird)|seeing double|double vision)\b"#,
        #"\b(?:can'?t walk straight|can'?t stand up straight|lost (?:my|his|her|their) balance|can'?t keep (?:my|his|her|their) balance)\b"#,
    ]

    static let triageDangerPatterns: [String: String] = [
        "chest_pain": #"\b(?:crushing|squeez\w*|spread\w*|radiat\w*|arm|jaw|neck|back|shoulder|sweat\w*|clammy|sick|nause\w*|throw(?:ing)? up|vomit\w*|dizzy|faint|lightheaded|worse|pressure|heavy|tight\w*|(?:trouble|hard|difficult|difficulty|struggling)\s+(?:to\s+)?breath\w*|can'?t breathe|cannot breathe|short(?:ness)? of breath|breathless|out of breath)\b"#,
        "faint": #"\b(?:chest|pound\w*|racing|flutter\w*|irregular|skipp\w*|blacked out|passed out|fainted|lost consciousness|collapsed|confused|numb|slurr\w*|can'?t see|(?:trouble|hard|difficult|difficulty|struggling)\s+(?:to\s+)?breath\w*|can'?t breathe|cannot breathe|short(?:ness)? of breath|breathless|out of breath)\b"#,
        "ingestion": #"\b(?:drowsy|sleepy|can'?t stay awake|hard to wake|won'?t wake|confused|seizure|seizing|shaking|blue|unconscious|passed out|on purpose|hurt (?:myself|themselves|himself|herself)|wanted to|meant to|intentional\w*|deliberately|to die|end it|(?:trouble|hard|difficult|difficulty|struggling)\s+(?:to\s+)?breath\w*|can'?t breathe|cannot breathe|short(?:ness)? of breath|breathless|out of breath)\b"#,
        "bleeding": #"\b(?:spurt\w*|squirt\w*|soak\w*|still (?:going|bleeding)|won'?t stop|not stopping|keeps bleeding|gushing|pouring|faint|dizzy|lightheaded|pale|cold|clammy|passing out|(?:trouble|hard|difficult|difficulty|struggling)\s+(?:to\s+)?breath\w*|can'?t breathe|cannot breathe|short(?:ness)? of breath|breathless|out of breath)\b"#,
    ]

    /// Every pattern above, so a test can prove each one compiles in ICU —
    /// `try? NSRegularExpression` would otherwise turn a bad one into a
    /// silent miss on a 911 turn.
    static let allPatterns: [String] = [
        selfHarmPattern,
        hurtSelfPattern,
        hurtSelfInjuryPattern,
        cantTalkRightPattern,
        oneSidedDeficitPattern,
        allergyComboPattern,
        bleedingPattern,
        bleedingTriagePattern,
        chokingPattern,
        headInjuryPattern,
        headInjuryRedFlagPattern,
        ingestionMedPattern,
        ingestionToxinPattern,
        childIngestionPattern,
        poisonedPattern,
        ingestionIntentPattern,
        ingestionDangerPattern,
        helperPronounPattern,
        firstPersonPattern,
        yesLeadPattern,
        noLeadPattern,
        clauseBreakPattern,
        triageCardiacCuePattern,
        triageIntentCuePattern,
    ] + strokeDomainPatterns + Array(triageDangerPatterns.values)

    // MARK: Copy

    static let emergencyOpen = "Call 911 now."
    static let emergencyCpr = "Start CPR: hard, fast chest compressions in the center of the chest — about 100–120 a minute, roughly 2 inches deep, letting the chest come all the way back up between each. If you're trained, add 2 rescue breaths every 30 compressions. Keep going until help arrives or the person starts to wake up."
    static let emergencyCprIfNeeded = "If they're not breathing normally, start CPR: hard, fast chest compressions in the center of the chest — about 100–120 a minute, roughly 2 inches deep, letting the chest come all the way back up between each. If you're trained, add 2 rescue breaths every 30 compressions. Keep going until help arrives or the person starts to wake up."
    static let cardiac = "Stop what you're doing and sit or lie down somewhere safe. Don't drive yourself, and unlock the door so help can get in."
    static let cardiacHelper = "Help them sit or lie down, don't let them drive, unlock the door and stay with them."
    static let stroke = "Note the time it started, don't eat or drink anything, don't drive, unlock the door and don't stay alone."
    static let strokeHelper = "Note the time it started, give them nothing to eat or drink, and stay with them."
    static let faint = "Lie down flat and stay down, don't get back on the equipment or drive, and keep someone with you if you can."
    static let faintHelper = "Lay them flat. If they don't wake up or aren't breathing normally, start CPR: hard, fast chest compressions in the center of the chest — about 100–120 a minute, roughly 2 inches deep, letting the chest come all the way back up between each. If you're trained, add 2 rescue breaths every 30 compressions. Keep going until help arrives or the person starts to wake up."
    static let patientFallback = "Unlock the door and stay on the line."
    static let choking = "If you can cough, keep coughing hard. If you can't breathe or cough, push your upper belly hard and fast against the back of a chair until it comes out."
    static let chokingHelper = "If they can't breathe, cough, or speak, give 5 firm back blows between the shoulder blades, then 5 quick upward thrusts just above the belly button. Keep alternating until it comes out. If they go limp, start CPR: hard, fast chest compressions in the center of the chest — about 100–120 a minute, roughly 2 inches deep, letting the chest come all the way back up between each. If you're trained, add 2 rescue breaths every 30 compressions. Keep going until help arrives or the person starts to wake up."
    static let bleeding = "Press hard on the wound with a clean cloth and don't let up. Add more cloth on top if it soaks through, sit or lie down, and unlock the door."
    static let bleedingHelper = "Press hard on the wound with a clean cloth and don't let up. Add more cloth on top if it soaks through, and keep them still and warm."
    static let allergy = "If you have an epinephrine auto-injector, use it now in your outer thigh. Sit up if breathing is hard, or lie down with your legs raised if you feel faint, and unlock the door."
    static let allergyHelper = "If they have an epinephrine auto-injector, help them use it now in the outer thigh. Keep them sitting up if breathing is hard, or lying down with legs raised if they feel faint, and stay with them."
    static let seizureHelper = "Clear space around them, cushion their head, and don't hold them down or put anything in their mouth. Turn them on their side once it eases and stay with them."
    static let head = "Stay still and sitting up, don't drive, and keep someone with you. Unlock the door so help can get in."
    static let headHelper = "Keep them still, don't let them drive or sleep alone, and stay with them. If they stop breathing, start CPR: hard, fast chest compressions in the center of the chest — about 100–120 a minute, roughly 2 inches deep, letting the chest come all the way back up between each. If you're trained, add 2 rescue breaths every 30 compressions. Keep going until help arrives or the person starts to wake up."
    static let ingestion = "Unlock the door, stay where you are, and keep the bottle or package with you."
    static let ingestionHelper = "Keep them awake and with you, and keep the bottle or package ready. If they stop breathing, start CPR: hard, fast chest compressions in the center of the chest — about 100–120 a minute, roughly 2 inches deep, letting the chest come all the way back up between each. If you're trained, add 2 rescue breaths every 30 compressions. Keep going until help arrives or the person starts to wake up."
    static let ingestionIntent = "Unlock the door and keep the bottle with you. You matter, and you don't have to face this alone. You can also call or text 988 any time."
    static let crisisLine = "You matter, and you don't have to face this alone. In the US you can call or text 988 for the Suicide & Crisis Lifeline, any time. If you're in immediate danger, call 911 now."
    static let boundaryInfo = "This is general first-aid information, not medical treatment."
    static let diagnosisReferOpen = "I can't tell from here — a doctor can check it properly. Meanwhile I'm glad to help with "
    static let medicationRefer = "That one's a call for your doctor or pharmacist — they know what you're on. I'm glad to help with the day-to-day stuff around it."
    static let eatingDisorderRefer = "That's not something to push through alone. A doctor or an eating-disorder helpline is the right help here, and I'm glad to help you fuel well in the meantime."
    static let chestClearedRefer = "Good that it was checked. Stick with what your doctor said, and call them if it changes or comes back. Call 911 if it's crushing, spreading, or you're short of breath."

    /// Ordered (topic, substring cues); burn words are whole-word.
    static let firstAidTopicCues: [(topic: String, cues: [String])] = [
        (topic: "cpr", cues: ["cpr", "rescue breath", "chest compression", "not breathing", "isn't breathing", "isnt breathing", "no pulse", "no heartbeat", "cardiac arrest", "aed", "defibrillat"]),
        (topic: "choking", cues: ["choking", "heimlich", "can't breathe", "cant breathe", "something stuck", "throat is closing"]),
        (topic: "bleeding", cues: ["bleeding", "blood", "tourniquet", "cut", "wound", "nosebleed"]),
        (topic: "unconscious", cues: ["collapsed", "passed out", "unconscious", "unresponsive", "won't wake", "wont wake", "fainted", "blacked out", "blacking out"]),
        (topic: "seizure", cues: ["seizure", "convulsing"]),
    ]

    static let firstAidSteps: [String: String] = [
        "cpr": "CPR: Make sure 911 is called and get an AED if one is nearby. Give hard, fast chest compressions in the center of the chest — about 100–120 compressions a minute, roughly 2 inches deep, letting the chest come all the way back up between each. If you're trained, add 2 rescue breaths every 30 compressions. Keep going until help arrives or the person starts to wake up.",
        "choking": "Choking: If they can't breathe, cough, or speak, call 911. Give 5 firm back blows between the shoulder blades, then 5 abdominal thrusts (hands just above the navel, quick inward-and-up pushes). Alternate until the object comes out or they can breathe.",
        "bleeding": "Severe bleeding: Call 911. Press firmly and directly on the wound with a clean cloth and don't let up — add more cloth on top if it soaks through. Keep the person warm and as still as possible.",
        "unconscious": "Someone unresponsive: Call 911 now. Check whether they're breathing normally. If they're not, start CPR (hard, fast chest compressions). If they are breathing, roll them onto their side and stay with them until help arrives.",
        "seizure": "Seizure: Call 911 if it lasts over 5 minutes, repeats, or they don't wake up. Clear space around them, cushion their head, and don't hold them down or put anything in their mouth. Turn them on their side once it eases.",
        "burn": "Burn: Cool it under cool (not ice-cold) running water for about 20 minutes and take off nearby rings or tight clothing before swelling starts. Cover it loosely with a clean, non-stick dressing or cling film. Don't pop blisters or put butter/toothpaste on it. Call 911 for a burn that's large, deep, on the face/hands/genitals, or from chemicals or electricity.",
        "general": "Call 911 (or have someone nearby call) and stay with the person. If they aren't breathing, start CPR — hard, fast chest compressions in the center of the chest. If they're bleeding heavily, press firmly on the wound with a clean cloth. Follow the 911 dispatcher's instructions.",
    ]

    /// "topic.subject" -> (lead, questions, net).
    static let triageCopy: [String: (lead: String, questions: [String], net: String)] = [
        "chest_pain.self": (lead: "Stop what you're doing and sit down.", questions: ["Is the pain crushing or squeezing, or spreading to your arm, jaw, neck or back?", "Any trouble breathing, sweating, or feeling sick?"], net: "If yes to any of that, call 911 now."),
        "faint.self": (lead: "Sit or lie down right now, wherever you are.", questions: ["Any chest pain, trouble breathing, or a heartbeat that's pounding and won't settle?", "Did you black out at all?"], net: "If yes to any of that, call 911 now."),
        "faint.other": (lead: "Help them sit or lie down right now.", questions: ["Do they have chest pain, trouble breathing, or a heartbeat that's pounding and won't settle?", "Did they black out at all?"], net: "If yes to any of that, call 911 now."),
        "ingestion.self": (lead: "Call Poison Control now at 1-800-222-1222. They'll tell you exactly what to do.", questions: ["Are you getting drowsy or confused, or is it hard to breathe?", "Did you take it to hurt yourself?"], net: "If yes to either, call 911 now."),
        "ingestion.other": (lead: "Call Poison Control now at 1-800-222-1222. They'll tell you exactly what to do, so keep the package with you.", questions: ["Are they getting drowsy or confused, or is it hard for them to breathe?", "Did they take it to hurt themselves?"], net: "If yes to either, call 911 now."),
        "bleeding.self": (lead: "Press hard on it with a clean cloth and keep pressing.", questions: ["Is it spurting, soaking through the cloth, or still going after 10 minutes of firm pressure?", "Do you feel faint or cold?"], net: "If yes to any of that, call 911 now."),
        "bleeding.other": (lead: "Press hard on it with a clean cloth and keep pressing.", questions: ["Is it spurting, soaking through the cloth, or still going after 10 minutes of firm pressure?", "Are they faint, pale, or cold?"], net: "If yes to any of that, call 911 now."),
    ]

    /// "topic.subject.band" -> resolution copy.
    static let triageResolution: [String: String] = [
        "chest_pain.self.refer_out": "Okay. Get it checked by a doctor today. Chest pain deserves a proper look even when it's mild, so no training until then. If it gets worse, spreads, or you're short of breath, call 911.",
        "chest_pain.self.coach_with_care": "Okay. Keep today easy with no chest work or hard cardio. If it's still there tomorrow, get it checked. If it changes, spreads, or you're short of breath, call 911.",
        "faint.self.coach_with_care": "Okay. Stay down until it passes, sip some water, and eat something if you haven't. Training is done for today. If it keeps happening, tell a doctor, and call 911 if chest pain or trouble breathing shows up.",
        "faint.self.refer_out": "Okay. Since it keeps happening, get checked by a doctor before you train again. For now, stay down until it passes and sip some water. Call 911 if chest pain or trouble breathing shows up.",
        "faint.other.coach_with_care": "Okay. Keep them sitting or lying down until it passes, with some water and something to eat. No more training for them today. If it keeps happening, they should see a doctor, and call 911 if chest pain or trouble breathing shows up.",
        "faint.other.refer_out": "Okay. Since it keeps happening, they should see a doctor before training again. For now, keep them sitting or lying down with some water. Call 911 if chest pain or trouble breathing shows up.",
        "ingestion.self.refer_out": "Okay. Stay on with Poison Control and do exactly what they say, and keep the bottle with you. If you get drowsy, confused, or it's hard to breathe, call 911.",
        "ingestion.other.refer_out": "Okay. Stay on with Poison Control and do exactly what they say, and keep the package with you. If they get drowsy, confused, or it's hard for them to breathe, call 911.",
        "bleeding.self.coach_with_care": "Okay. Keep steady pressure until it stops, then clean it gently and cover it. If it starts again, looks deep, or came from something dirty or rusty, get it looked at today. If it won't stop, call 911.",
        "bleeding.self.refer_out": "Okay. Keep pressure on it and get it looked at today. That one needs a proper look. If it won't stop or you feel faint, call 911.",
        "bleeding.other.coach_with_care": "Okay. Keep steady pressure on it until it stops, then clean it gently and cover it. If it starts again, looks deep, or came from something dirty or rusty, they should get it looked at today. If it won't stop, call 911.",
        "bleeding.other.refer_out": "Okay. Keep pressure on it and get them seen today. That one needs a proper look. If it won't stop or they feel faint, call 911.",
    ]

    /// "kind.subject" -> [new, familiar, bond] check-in lines.
    static let checkIn: [String: [String]] = [
        "emergency.self": ["You were in an emergency. How are you feeling now?", "You were in an emergency. I'm glad you're back. How are you feeling now?", "Hey. You were in an emergency, and I've been hoping you're okay. How are you feeling now? Take your time."],
        "emergency.other": ["That was an emergency. How are you feeling now, and how are they?", "That was an emergency, and you stayed with them. How are you feeling now, and how are they?", "Hey. That was a lot to carry, and you stayed with them. How are you feeling now, and how are they doing?"],
        "self_harm.self": ["You were in a really hard moment. How are you feeling now? 988 is there any time, call or text.", "You were in a really hard moment, and I'm glad you're still here talking to me. How are you feeling now? 988 is there any time, call or text.", "Hey. I'm really glad you're here. You were in a really hard moment. How are you feeling now? 988 is there any time, call or text."],
        "resolved.self": ["That could have been an emergency. How are you feeling now?", "That could have been an emergency. I'm glad you told me. How are you feeling now?", "Hey. That could have been an emergency, and I'm glad you told me. How are you feeling now? Take your time."],
        "resolved.other": ["That could have been an emergency. How are you feeling now, and how are they?", "That could have been an emergency, and you stayed with them. How are you feeling now, and how are they?", "Hey. That could have been a lot, and you stayed with them. How are you feeling now, and how are they doing?"],
    ]
}
