import SwiftUI

extension ExerciseLibrary {

    /// Extra lifts so the library is a real gym floor, not a starter pack.
    static let expansion: [ExerciseDefinition] = expansionPush + expansionShoulders + expansionPull + expansionOlympic + expansionArms + expansionLegs + expansionCalves + expansionCore + expansionConditioning + expansionMobility + expansionTools + expansionCalisthenics + expansionSports

    // ── More chest / horizontal push ──────────────────────────────────────────────
    static let expansionPush: [ExerciseDefinition] = [
        .make("Decline Dumbbell Press", .horizontalPush, .dumbbell, primary: [.chest], secondary: [.triceps], cues: ["Lower with a stretch", "Press up and slightly in"], faults: ["Flaring the elbows"], pain: ["Shoulder"], subs: ["Decline Bench Press"], note: "Lower-chest emphasis with a free range."),
        .make("Incline Machine Chest Press", .horizontalPush, .machine, primary: [.chest, .frontDelts], secondary: [.triceps], cues: ["Set the seat so handles hit upper chest", "Don't bounce the stack"], subs: ["Incline Dumbbell Press"], note: "Stable upper-chest volume."),
        .make("Smith Machine Bench Press", .horizontalPush, .machine, primary: [.chest], secondary: [.frontDelts, .triceps], cues: ["Bar path over mid-chest", "Feet planted"], pain: ["Shoulder"], subs: ["Barbell Bench Press"], note: "Fixed-path bench for confidence under load."),
        .make("Floor Press", .horizontalPush, .barbell, primary: [.chest, .triceps], secondary: [.frontDelts], level: .intermediate, sets: 4, repLow: 5, repHigh: 8, rest: 120, cues: ["Upper arms tap the floor", "Pause, then press"], pain: ["Shoulder"], subs: ["Dumbbell Bench Press"], note: "Short-range lockout strength."),
        .make("Dumbbell Fly", .isolation, .dumbbell, primary: [.chest], secondary: [.frontDelts], mechanic: .isolation, repLow: 12, repHigh: 15, rest: 60, cues: ["Soft elbows, hug a barrel", "Don't go so deep the shoulders dump"], faults: ["Pressing instead of flying"], pain: ["Shoulder"], subs: ["Cable Chest Fly"], note: "Stretch-biased chest isolation."),
        .make("Incline Cable Fly", .isolation, .cable, primary: [.chest, .frontDelts], mechanic: .isolation, rest: 60, cues: ["Low pulleys, sweep up and in"], pain: ["Shoulder"], subs: ["Incline Dumbbell Press"], note: "Upper-chest fly with constant tension."),
        .make("Low-to-High Cable Fly", .isolation, .cable, primary: [.chest], secondary: [.frontDelts], mechanic: .isolation, rest: 60, cues: ["Start low, finish at eye line"], pain: ["Shoulder"], subs: ["Cable Chest Fly"], note: "Clavicular-fiber bias."),
        .make("Squeeze Press", .horizontalPush, .dumbbell, primary: [.chest], secondary: [.triceps], rest: 75, cues: ["Press the bells together the whole way"], subs: ["Dumbbell Bench Press"], note: "Inner-chest tension under a press."),
        .make("Incline Push-Up", .horizontalPush, .bodyweight, primary: [.chest], secondary: [.triceps, .abs], rest: 45, cues: ["Hands on a bench, body in one line"], regress: ["Push-Up"], progress: ["Push-Up"], subs: ["Push-Up"], note: "The honest push-up regression."),
        .make("Decline Push-Up", .horizontalPush, .bodyweight, primary: [.chest, .frontDelts], secondary: [.triceps], level: .intermediate, rest: 60, cues: ["Feet elevated, don't pike"], pain: ["Shoulder"], subs: ["Incline Dumbbell Press"], note: "Upper-chest bodyweight overload."),
        .make("Single-Arm Cable Chest Press", .horizontalPush, .cable, primary: [.chest], secondary: [.abs, .triceps], unilateral: true, rest: 75, cues: ["Press from the ribs, don't rotate"], subs: ["Dumbbell Bench Press"], note: "Anti-rotation press."),
        .make("Landmine Chest Press", .horizontalPush, .barbell, primary: [.chest], secondary: [.frontDelts, .triceps], unilateral: true, rest: 75, cues: ["Press on the arc, square the ribs"], pain: ["Shoulder"], subs: ["Landmine Press"], note: "Shoulder-friendly pressing angle."),
        .make("Weighted Dip", .horizontalPush, .bodyweight, primary: [.chest, .triceps], secondary: [.frontDelts], level: .advanced, rest: 120, cues: ["Belt the load", "Lean for chest, upright for triceps"], pain: ["Shoulder"], regress: ["Chest Dip"], subs: ["Chest Dip"], note: "Overload the dip."),
        .make("Ring Push-Up", .horizontalPush, .trx, primary: [.chest], secondary: [.abs, .triceps], level: .intermediate, rest: 75, cues: ["Rings tight, body rigid"], faults: ["Sagging hips"], subs: ["Push-Up"], note: "Unstable push-up for the trunk."),
        .make("Hex Press", .horizontalPush, .dumbbell, primary: [.chest], secondary: [.triceps], rest: 75, cues: ["Bells glued together on the chest"], subs: ["Squeeze Press"], note: "Constant squeeze under a short press."),
        .make("Standing Cable Chest Press", .horizontalPush, .cable, primary: [.chest], secondary: [.abs, .triceps], rest: 75, cues: ["Staggered stance, punch from the ribs"], subs: ["Machine Chest Press"], note: "Athletic standing press."),
    ]

    // ── More delts ──────────────────────────────────────────────
    static let expansionShoulders: [ExerciseDefinition] = [
        .make("Z Press", .verticalPush, .barbell, primary: [.frontDelts], secondary: [.triceps, .abs], level: .advanced, sets: 4, repLow: 5, repHigh: 8, rest: 120, cues: ["Sit tall on the floor", "No leaning back"], pain: ["Shoulder", "Lower Back"], subs: ["Overhead Press"], note: "Overhead press with nowhere to hide."),
        .make("Bottoms-Up Kettlebell Press", .verticalPush, .kettlebell, primary: [.frontDelts], secondary: [.forearms, .abs], unilateral: true, rest: 75, cues: ["Horn up, crush the handle", "Slow press"], pain: ["Shoulder"], subs: ["Seated Dumbbell Shoulder Press"], note: "Stability and rotator-cuff demand."),
        .make("Lean-Away Lateral Raise", .isolation, .dumbbell, primary: [.sideDelts], mechanic: .isolation, unilateral: true, rest: 45, cues: ["Hold a rack and lean", "Lead with the elbow"], faults: ["Shrugging"], subs: ["Lateral Raise"], note: "Longer lever on the side delt."),
        .make("Machine Lateral Raise", .isolation, .machine, primary: [.sideDelts], mechanic: .isolation, rest: 45, cues: ["Elbows in the pads", "No swinging"], subs: ["Lateral Raise"], note: "Strict width work."),
        .make("Cable Front Raise", .isolation, .cable, primary: [.frontDelts], mechanic: .isolation, rest: 45, cues: ["Raise to eye line, don't swing"], subs: ["Front Raise"], note: "Constant-tension front delt."),
        .make("Prone Y Raise", .isolation, .dumbbell, primary: [.rearDelts, .upperBack], secondary: [.traps], mechanic: .isolation, force: .pull, rest: 45, cues: ["Thumbs up, long arms", "Don't yank the neck"], subs: ["Rear Delt Fly"], note: "Lower-trap and rear-delt health."),
        .make("Cuban Rotation", .isolation, .dumbbell, primary: [.rearDelts], secondary: [.traps], mechanic: .isolation, force: .pull, rest: 45, cues: ["Elbows at 90, rotate the hands up"], pain: ["Shoulder"], subs: ["Face Pull"], note: "External-rotation strength."),
        .make("Landmine Lateral Raise", .isolation, .barbell, primary: [.sideDelts], mechanic: .isolation, unilateral: true, rest: 45, cues: ["Sweep the bar out on the arc"], subs: ["Lateral Raise"], note: "Side-delt raise on a landmine."),
        .make("Seated Dumbbell Lateral Raise", .isolation, .dumbbell, primary: [.sideDelts], mechanic: .isolation, rest: 45, cues: ["No leg drive", "Pause at the top"], subs: ["Lateral Raise"], note: "Strict seated laterals."),
        .make("Dumbbell Push Press", .verticalPush, .dumbbell, primary: [.frontDelts], secondary: [.quads, .triceps], modality: .power, level: .intermediate, sets: 4, repLow: 4, repHigh: 8, rest: 120, cues: ["Short dip, punch the bells"], pain: ["Shoulder"], subs: ["Push Press"], note: "Leg drive into a dumbbell press."),
        .make("Behind-the-Neck Press", .verticalPush, .barbell, primary: [.frontDelts, .sideDelts], secondary: [.triceps], level: .advanced, rest: 120, cues: ["Only if the shoulders allow a clean path"], pain: ["Shoulder"], subs: ["Overhead Press"], note: "Skip it if the shoulder doesn't love it."),
    ]

    // ── More pull ──────────────────────────────────────────────
    static let expansionPull: [ExerciseDefinition] = [
        .make("Wide-Grip Pull-Up", .verticalPull, .bodyweight, primary: [.lats], secondary: [.upperBack, .biceps], force: .pull, level: .intermediate, rest: 120, cues: ["Wide but not extreme", "Chest to the bar"], regress: ["Lat Pulldown"], subs: ["Pull-Up"], note: "Lat-width bias."),
        .make("Neutral-Grip Pull-Up", .verticalPull, .bodyweight, primary: [.lats], secondary: [.biceps], force: .pull, level: .intermediate, rest: 120, cues: ["Palms in, drive elbows down"], subs: ["Chin-Up"], note: "Shoulder-friendly pull-up."),
        .make("Assisted Pull-Up", .verticalPull, .machine, primary: [.lats], secondary: [.biceps], force: .pull, cues: ["Use the least assist that keeps full range"], progress: ["Pull-Up"], subs: ["Lat Pulldown"], note: "The honest path to a pull-up."),
        .make("Chest-Supported Dumbbell Row", .horizontalPull, .dumbbell, primary: [.upperBack, .lats], secondary: [.biceps], force: .pull, rest: 75, cues: ["Chest on the bench", "Pull and pause"], subs: ["Chest-Supported Row"], note: "Rowing volume with a quiet lower back."),
        .make("Meadows Row", .horizontalPull, .barbell, primary: [.lats, .upperBack], secondary: [.obliques], force: .pull, level: .intermediate, unilateral: true, cues: ["Landmine, staggered stance", "Row to the hip"], pain: ["Lower Back"], subs: ["Dumbbell Row"], note: "Ugly, effective lat row."),
        .make("Seal Row", .horizontalPull, .barbell, primary: [.upperBack], secondary: [.lats, .biceps], force: .pull, cues: ["Lie face-down, row from a dead hang"], subs: ["Chest-Supported Row"], note: "Zero cheating row."),
        .make("Single-Arm Cable Row", .horizontalPull, .cable, primary: [.lats], secondary: [.biceps, .abs], force: .pull, unilateral: true, rest: 75, cues: ["Pull to the hip", "Don't twist the pelvis"], subs: ["Dumbbell Row"], note: "Long-range lat row."),
        .make("Underhand Lat Pulldown", .verticalPull, .cable, primary: [.lats, .biceps], force: .pull, rest: 75, cues: ["Supinated grip, bar to the upper chest"], subs: ["Lat Pulldown"], note: "Chin-up pattern on a stack."),
        .make("Straight-Arm Dumbbell Pullover", .isolation, .dumbbell, primary: [.lats], secondary: [.chest], mechanic: .isolation, force: .pull, rest: 60, cues: ["Soft elbows, stretch over the head"], pain: ["Shoulder"], subs: ["Straight-Arm Pulldown"], note: "Lat stretch with a dumbbell."),
        .make("Cable Pullover", .isolation, .cable, primary: [.lats], mechanic: .isolation, force: .pull, rest: 45, cues: ["Rope to the hips, ribs down"], subs: ["Straight-Arm Pulldown"], note: "Lat isolation with a rope."),
        .make("Renegade Row", .horizontalPull, .dumbbell, primary: [.lats, .abs], secondary: [.upperBack], force: .pull, unilateral: true, rest: 75, cues: ["Plank first", "Row without opening the hips"], faults: ["Rotating the pelvis"], subs: ["Dumbbell Row"], note: "Row plus anti-rotation."),
        .make("Gorilla Row", .horizontalPull, .kettlebell, primary: [.lats, .upperBack], secondary: [.biceps], force: .pull, rest: 75, cues: ["Hinge over two bells", "Row one, park it, switch"], pain: ["Lower Back"], subs: ["Dumbbell Row"], note: "Alternating hinge row."),
        .make("Landmine Row", .horizontalPull, .barbell, primary: [.upperBack, .lats], secondary: [.biceps], force: .pull, cues: ["Neutral handle if you have one", "Pull to the ribs"], pain: ["Lower Back"], subs: ["T-Bar Row"], note: "T-bar pattern without the station."),
        .make("TRX Row", .horizontalPull, .trx, primary: [.upperBack], secondary: [.lats, .biceps], force: .pull, rest: 60, cues: ["Walk the feet to scale", "Chest to the handles"], subs: ["Inverted Row"], note: "Scalable suspension row."),
        .make("Helms Row", .horizontalPull, .dumbbell, primary: [.upperBack], secondary: [.lats], force: .pull, rest: 75, cues: ["Chest on a high bench", "Elbows flare slightly"], subs: ["Chest-Supported Dumbbell Row"], note: "Upper-back focus with a chest pad."),
        .make("Machine High Row", .horizontalPull, .machine, primary: [.upperBack, .lats], secondary: [.biceps], force: .pull, rest: 75, cues: ["Pull to the upper chest"], subs: ["Seated Cable Row"], note: "High-elbow machine row."),
        .make("Yates Row", .horizontalPull, .barbell, primary: [.upperBack], secondary: [.lats, .biceps], force: .pull, level: .intermediate, cues: ["More upright than a Pendlay", "Pull to the waist"], pain: ["Lower Back"], subs: ["Barbell Row"], note: "Underhand, slightly upright row."),
        .make("Kettlebell Row", .horizontalPull, .kettlebell, primary: [.lats], secondary: [.biceps], force: .pull, unilateral: true, rest: 75, cues: ["Pack the shoulder", "Pull the bell to the hip"], subs: ["Dumbbell Row"], note: "Single-arm row with a kettlebell."),
    ]

    // ── Olympic + power ──────────────────────────────────────────────
    static let expansionOlympic: [ExerciseDefinition] = [
        .make("Power Clean", .hinge, .barbell, primary: [.fullBody], secondary: [.glutes, .traps, .quads], force: .pull, modality: .power, level: .advanced, sets: 5, repLow: 2, repHigh: 4, rest: 150, met: 7.0, cues: ["Jump the bar, pull under", "Catch in a quarter squat"], faults: ["Reverse curling the bar"], pain: ["Lower Back", "Wrist"], subs: ["Kettlebell Swing"], note: "Classic triple-extension power."),
        .make("Hang Clean", .hinge, .barbell, primary: [.fullBody], secondary: [.glutes, .traps], force: .pull, modality: .power, level: .advanced, sets: 5, repLow: 2, repHigh: 4, rest: 150, met: 6.5, cues: ["Start above the knee", "Aggressive hip extension"], pain: ["Lower Back"], subs: ["Power Clean"], note: "Clean from the hang."),
        .make("Hang Power Clean", .hinge, .barbell, primary: [.fullBody], secondary: [.glutes, .traps], force: .pull, modality: .power, level: .advanced, sets: 5, repLow: 2, repHigh: 4, rest: 150, met: 6.5, cues: ["Hang, jump, catch high"], subs: ["Hang Clean"], note: "Power catch from the hang."),
        .make("Clean and Jerk", .hinge, .barbell, primary: [.fullBody], secondary: [.frontDelts, .quads], force: .pull, modality: .power, level: .advanced, sets: 4, repLow: 1, repHigh: 3, rest: 180, met: 8.0, cues: ["Clean, reset, then jerk"], pain: ["Shoulder", "Lower Back", "Wrist"], subs: ["Power Clean"], note: "The full Olympic pair."),
        .make("Power Snatch", .hinge, .barbell, primary: [.fullBody], secondary: [.glutes, .frontDelts], force: .pull, modality: .power, level: .advanced, sets: 5, repLow: 2, repHigh: 3, rest: 150, met: 7.5, cues: ["Wide grip, bar close", "Catch overhead in a quarter squat"], pain: ["Shoulder", "Lower Back"], subs: ["Dumbbell Snatch"], note: "Fast overhead triple extension."),
        .make("Hang Snatch", .hinge, .barbell, primary: [.fullBody], secondary: [.glutes, .frontDelts], force: .pull, modality: .power, level: .advanced, sets: 5, repLow: 2, repHigh: 3, rest: 150, met: 7.0, cues: ["Hang start, aggressive finish overhead"], pain: ["Shoulder"], subs: ["Power Snatch"], note: "Snatch from the hang."),
        .make("Push Jerk", .verticalPush, .barbell, primary: [.frontDelts], secondary: [.quads, .triceps], modality: .power, level: .advanced, sets: 4, repLow: 2, repHigh: 5, rest: 150, met: 6.5, cues: ["Dip, drive, drop under"], pain: ["Shoulder", "Wrist"], subs: ["Push Press"], note: "Re-bend the knees to receive."),
        .make("Split Jerk", .verticalPush, .barbell, primary: [.frontDelts], secondary: [.quads, .triceps], modality: .power, level: .advanced, sets: 4, repLow: 1, repHigh: 3, rest: 180, met: 7.0, cues: ["Split the feet, lock the arms"], pain: ["Shoulder"], subs: ["Push Jerk"], note: "Classic jerk recovery."),
        .make("Dumbbell Snatch", .hinge, .dumbbell, primary: [.fullBody], secondary: [.glutes, .frontDelts], force: .pull, modality: .power, level: .intermediate, unilateral: true, sets: 4, repLow: 5, repHigh: 8, met: 7.0, cues: ["Hike, punch overhead in one path"], pain: ["Shoulder", "Lower Back"], subs: ["Kettlebell Snatch"], note: "Single-arm power from the floor."),
        .make("Kettlebell Snatch", .hinge, .kettlebell, primary: [.fullBody], secondary: [.glutes, .frontDelts], force: .pull, modality: .power, level: .intermediate, unilateral: true, sets: 4, repLow: 6, repHigh: 10, rest: 75, met: 8.0, cues: ["Punch through, don't crash the forearm"], pain: ["Shoulder"], subs: ["Kettlebell Swing"], note: "Cardio plus power in one bell."),
        .make("Clean Pull", .hinge, .barbell, primary: [.glutes, .hamstrings, .traps], secondary: [.forearms], force: .pull, modality: .power, level: .intermediate, sets: 4, repLow: 3, repHigh: 5, rest: 150, met: 6.5, cues: ["Deadlift, then jump the bar"], pain: ["Lower Back"], subs: ["Conventional Deadlift"], note: "Olympic pull without the catch."),
        .make("High Pull", .hinge, .barbell, primary: [.traps, .sideDelts], secondary: [.glutes], force: .pull, modality: .power, level: .intermediate, met: 6.0, cues: ["Hips first, elbows high and outside"], pain: ["Shoulder"], subs: ["Upright Row"], note: "Explosive pull to the chest."),
    ]

    // ── More arms + grip ──────────────────────────────────────────────
    static let expansionArms: [ExerciseDefinition] = [
        .make("Close-Grip Push-Up", .horizontalPush, .bodyweight, primary: [.triceps, .chest], secondary: [.abs], rest: 60, cues: ["Hands under the shoulders", "Elbows tight"], subs: ["Close-Grip Bench Press"], note: "Triceps-biased push-up."),
        .make("Diamond Push-Up", .horizontalPush, .bodyweight, primary: [.triceps], secondary: [.chest], level: .intermediate, rest: 60, cues: ["Thumbs and index fingers touch", "Elbows in"], pain: ["Wrist"], subs: ["Close-Grip Push-Up"], note: "Hard lockout triceps work."),
        .make("EZ-Bar Curl", .isolation, .barbell, primary: [.biceps], secondary: [.forearms], mechanic: .isolation, force: .pull, rest: 60, cues: ["Elbows pinned", "Don't swing"], pain: ["Wrist"], subs: ["Barbell Curl"], note: "Wrist-friendlier barbell curl."),
        .make("Concentration Curl", .isolation, .dumbbell, primary: [.biceps], mechanic: .isolation, force: .pull, unilateral: true, rest: 45, cues: ["Elbow on the inner thigh", "Squeeze the top"], subs: ["Dumbbell Curl"], note: "Peak isolation, zero cheat."),
        .make("Spider Curl", .isolation, .dumbbell, primary: [.biceps], mechanic: .isolation, force: .pull, rest: 60, cues: ["Chest on an incline, arms hang"], subs: ["Incline Dumbbell Curl"], note: "Shortened-range biceps."),
        .make("Bayesian Cable Curl", .isolation, .cable, primary: [.biceps], mechanic: .isolation, force: .pull, unilateral: true, rest: 45, cues: ["Face away, stretch the long head"], subs: ["Cable Curl"], note: "Long-head stretch curl."),
        .make("Zottman Curl", .isolation, .dumbbell, primary: [.biceps, .forearms], mechanic: .isolation, force: .pull, rest: 45, cues: ["Supinate up, pronate down"], subs: ["Dumbbell Curl"], note: "Biceps up, forearms down."),
        .make("Cross-Body Hammer Curl", .isolation, .dumbbell, primary: [.biceps, .forearms], mechanic: .isolation, force: .pull, rest: 45, cues: ["Neutral grip across the body"], subs: ["Hammer Curl"], note: "Brachialis emphasis."),
        .make("Incline Hammer Curl", .isolation, .dumbbell, primary: [.biceps], secondary: [.forearms], mechanic: .isolation, force: .pull, rest: 60, cues: ["Arms hang back, hammer the curl"], subs: ["Hammer Curl"], note: "Long-head hammer curl."),
        .make("Rope Pushdown", .isolation, .cable, primary: [.triceps], mechanic: .isolation, rest: 45, cues: ["Split the rope at lockout"], pain: ["Elbow"], subs: ["Triceps Pushdown"], note: "Lateral-head finish."),
        .make("Triceps Kickback", .isolation, .dumbbell, primary: [.triceps], mechanic: .isolation, unilateral: true, rest: 45, cues: ["Upper arm glued to the side", "Full lockout"], pain: ["Elbow"], subs: ["Triceps Pushdown"], note: "Shortened triceps squeeze."),
        .make("Overhead Cable Extension", .isolation, .cable, primary: [.triceps], mechanic: .isolation, rest: 60, cues: ["Face away, stretch the long head"], pain: ["Elbow"], subs: ["Overhead Triceps Extension"], note: "Cable long-head work."),
        .make("JM Press", .horizontalPush, .barbell, primary: [.triceps], secondary: [.chest], level: .advanced, cues: ["Lower toward the chin, elbows in"], pain: ["Elbow", "Wrist"], subs: ["Close-Grip Bench Press"], note: "Hybrid skull crusher and close-grip."),
        .make("Tate Press", .isolation, .dumbbell, primary: [.triceps], mechanic: .isolation, rest: 60, cues: ["Bells over the chest, elbows out"], pain: ["Elbow"], subs: ["Skull Crusher"], note: "Elbow-friendly for some, not all."),
        .make("Wrist Extension", .isolation, .dumbbell, primary: [.forearms], mechanic: .isolation, force: .pull, repLow: 15, repHigh: 20, rest: 45, met: 3.0, cues: ["Forearm on a bench, extend the wrist"], subs: ["Reverse Curl"], note: "Extensor work for elbow health."),
        .make("Behind-the-Back Wrist Curl", .isolation, .barbell, primary: [.forearms], mechanic: .isolation, force: .pull, repLow: 12, repHigh: 20, rest: 45, met: 3.5, cues: ["Bar behind the hips, curl the wrists"], subs: ["Wrist Curl"], note: "Forearm flexors from a different angle."),
        .make("Towel Curl", .isolation, .dumbbell, primary: [.forearms, .biceps], mechanic: .isolation, force: .pull, rest: 45, cues: ["Loop a towel through the handle and crush it"], subs: ["Hammer Curl"], note: "Grip plus curl."),
    ]

    // ── More squat, hinge, lunge ──────────────────────────────────────────────
    static let expansionLegs: [ExerciseDefinition] = [
        .make("Pause Back Squat", .squat, .barbell, primary: [.quads, .glutes], secondary: [.abs], level: .intermediate, sets: 4, repLow: 4, repHigh: 6, rest: 180, cues: ["Three-count in the hole", "Don't bounce"], pain: ["Knee", "Lower Back"], subs: ["Back Squat"], note: "Strength out of the hole."),
        .make("Box Squat", .squat, .barbell, primary: [.glutes, .quads], secondary: [.hamstrings], level: .intermediate, rest: 150, cues: ["Sit back to the box", "Pause, then explode"], pain: ["Knee"], subs: ["Back Squat"], note: "Posterior-chain squat pattern."),
        .make("Safety Bar Squat", .squat, .barbell, primary: [.quads, .glutes], secondary: [.upperBack], level: .intermediate, rest: 150, cues: ["Stay tall, camber does the rest"], pain: ["Knee"], subs: ["Back Squat"], note: "Easier on the shoulders than a low bar."),
        .make("Belt Squat", .squat, .machine, primary: [.quads, .glutes], rest: 120, cues: ["Load the hips, spine stays quiet"], pain: ["Knee"], subs: ["Goblet Squat"], note: "Heavy legs, almost no spinal load."),
        .make("Heels-Elevated Goblet Squat", .squat, .dumbbell, primary: [.quads], secondary: [.glutes], rest: 75, cues: ["Plates under the heels", "Sit between the knees"], pain: ["Knee"], subs: ["Goblet Squat"], note: "Quad-biased squat with a dumbbell."),
        .make("Split Squat", .lunge, .dumbbell, primary: [.quads, .glutes], secondary: [.hamstrings], unilateral: true, rest: 75, cues: ["In-place split, drop straight down"], pain: ["Knee"], subs: ["Bulgarian Split Squat"], note: "The quieter cousin of the Bulgarian."),
        .make("Front-Foot Elevated Split Squat", .lunge, .dumbbell, primary: [.quads], secondary: [.glutes], unilateral: true, rest: 75, cues: ["Front foot on a plate for extra range"], pain: ["Knee"], subs: ["Split Squat"], note: "Longer quad stretch."),
        .make("Lateral Lunge", .lunge, .dumbbell, primary: [.adductors, .quads], secondary: [.glutes], unilateral: true, rest: 75, cues: ["Sit into the hip, other leg straight"], pain: ["Knee"], subs: ["Cossack Squat"], note: "Frontal-plane strength."),
        .make("Curtsy Lunge", .lunge, .dumbbell, primary: [.glutes, .quads], secondary: [.abductors], unilateral: true, rest: 75, cues: ["Step back and across", "Keep the pelvis square"], pain: ["Knee"], subs: ["Reverse Lunge"], note: "Glute medius plus the lunge."),
        .make("Pistol Squat", .squat, .bodyweight, primary: [.quads, .glutes], secondary: [.abs], level: .advanced, unilateral: true, cues: ["Reach the other leg, sit between"], pain: ["Knee"], regress: ["Box Squat"], subs: ["Bulgarian Split Squat"], note: "Single-leg squat skill."),
        .make("Pendulum Squat", .squat, .machine, primary: [.quads], secondary: [.glutes], level: .intermediate, rest: 120, cues: ["Let the arc take the knees forward"], pain: ["Knee"], subs: ["Hack Squat"], note: "Deep quad machine."),
        .make("Single-Leg Press", .squat, .machine, primary: [.quads, .glutes], secondary: [.hamstrings], unilateral: true, cues: ["One foot, don't twist the hip"], pain: ["Knee"], subs: ["Leg Press"], note: "Unilateral machine squat."),
        .make("Deficit Deadlift", .hinge, .barbell, primary: [.hamstrings, .glutes, .lowerBack], secondary: [.lats], force: .pull, level: .advanced, sets: 4, repLow: 3, repHigh: 5, rest: 210, cues: ["Stand on plates", "Stay over the bar"], pain: ["Lower Back"], subs: ["Conventional Deadlift"], note: "Longer pull off the floor."),
        .make("Stiff-Leg Deadlift", .hinge, .barbell, primary: [.hamstrings], secondary: [.glutes, .lowerBack], force: .pull, level: .intermediate, rest: 120, cues: ["Keep the knees almost locked", "Bar stays close to the legs"], pain: ["Lower Back"], subs: ["Romanian Deadlift"], note: "Hamstring stretch with a straighter knee."),
        .make("Dumbbell Romanian Deadlift", .hinge, .dumbbell, primary: [.hamstrings, .glutes], secondary: [.lowerBack], force: .pull, cues: ["Bells drag the thighs", "Hinge, don't squat"], pain: ["Lower Back"], subs: ["Romanian Deadlift"], note: "RDL you can do anywhere."),
        .make("Single-Leg Romanian Deadlift", .hinge, .dumbbell, primary: [.hamstrings, .glutes], secondary: [.abs], force: .pull, unilateral: true, rest: 75, cues: ["Hinge on one leg, square hips"], pain: ["Lower Back"], subs: ["Romanian Deadlift"], note: "Balance plus the hinge."),
        .make("B-Stance Romanian Deadlift", .hinge, .barbell, primary: [.hamstrings, .glutes], secondary: [.lowerBack], force: .pull, cues: ["Kickstand the back foot", "Load the front hip"], pain: ["Lower Back"], subs: ["Single-Leg Romanian Deadlift"], note: "Almost-unilateral RDL."),
        .make("Glute Ham Raise", .isolation, .machine, primary: [.hamstrings], secondary: [.glutes], mechanic: .isolation, force: .pull, level: .advanced, cues: ["Hinge then curl", "Control the eccentric"], subs: ["Nordic Curl"], note: "Posterior-chain machine that actually works."),
        .make("Reverse Hyper", .hinge, .machine, primary: [.glutes, .lowerBack], secondary: [.hamstrings], force: .pull, rest: 75, cues: ["Swing from the hips, not the spine"], pain: ["Lower Back"], subs: ["Back Extension"], note: "Decompressing posterior-chain work."),
        .make("Cable Glute Kickback", .isolation, .cable, primary: [.glutes], secondary: [.hamstrings], mechanic: .isolation, unilateral: true, rest: 45, cues: ["Ankle strap, kick back without arching"], subs: ["Hip Thrust"], note: "Glute isolation on a cable."),
        .make("Single-Leg Hip Thrust", .hinge, .dumbbell, primary: [.glutes], secondary: [.hamstrings], unilateral: true, rest: 75, cues: ["One foot, full lockout, no twist"], subs: ["Hip Thrust"], note: "Unilateral glute lockout."),
        .make("Frog Pump", .hinge, .bodyweight, primary: [.glutes], repLow: 20, repHigh: 30, rest: 45, cues: ["Soles together, thrust and squeeze"], subs: ["Glute Bridge"], note: "High-rep glute pump."),
        .make("Reverse Nordic Curl", .isolation, .bodyweight, primary: [.quads], mechanic: .isolation, level: .advanced, rest: 75, cues: ["Kneel, lean back with a straight line"], pain: ["Knee"], subs: ["Leg Extension"], note: "Quad eccentric from the hip."),
        .make("Smith Machine Squat", .squat, .machine, primary: [.quads, .glutes], rest: 120, cues: ["Feet slightly forward", "Control the descent"], pain: ["Knee"], subs: ["Back Squat"], note: "Guided squat path."),
        .make("Anderson Squat", .squat, .barbell, primary: [.quads, .glutes], secondary: [.abs], level: .advanced, rest: 180, cues: ["Start from pins in the hole"], pain: ["Knee", "Lower Back"], subs: ["Pause Back Squat"], note: "Dead-stop squat strength."),
        .make("Jefferson Deadlift", .hinge, .barbell, primary: [.glutes, .quads, .adductors], secondary: [.lowerBack], force: .pull, level: .advanced, rest: 150, cues: ["Straddle the bar, stay tall"], pain: ["Lower Back"], subs: ["Sumo Deadlift"], note: "Odd stance, honest hips."),
        .make("Wall Ball", .squat, .medicineBall, primary: [.quads, .frontDelts], secondary: [.cardio], modality: .conditioning, rest: 60, met: 8.0, cues: ["Squat, then throw to the target"], pain: ["Knee", "Shoulder"], subs: ["Thruster"], note: "Squat plus throw."),
        .make("Medicine Ball Slam", .hinge, .medicineBall, primary: [.abs, .lats], secondary: [.cardio], modality: .conditioning, rest: 45, met: 8.0, cues: ["Reach tall, slam through the floor"], subs: ["Battle Ropes"], note: "Power plus a heartbeat."),
        .make("Thruster", .squat, .barbell, primary: [.quads, .frontDelts], secondary: [.cardio], modality: .conditioning, level: .intermediate, met: 8.5, cues: ["Front squat into a press, one piece"], pain: ["Knee", "Shoulder"], subs: ["Push Press"], note: "The lung-burner compound."),
        .make("Jumping Lunge", .lunge, .bodyweight, primary: [.quads, .glutes], secondary: [.cardio], modality: .power, unilateral: true, rest: 60, cues: ["Switch in the air, land quiet"], pain: ["Knee"], subs: ["Walking Lunge"], note: "Plyometric split squat."),
        .make("Skater Jump", .gait, .bodyweight, primary: [.glutes, .abductors], secondary: [.cardio], modality: .power, unilateral: true, rest: 45, cues: ["Bound sideways, stick the landing"], pain: ["Knee", "Ankle"], subs: ["Box Jump"], note: "Lateral power."),
    ]

    // ── Calves + shins ──────────────────────────────────────────────
    static let expansionCalves: [ExerciseDefinition] = [
        .make("Donkey Calf Raise", .isolation, .machine, primary: [.calves], mechanic: .isolation, repLow: 12, repHigh: 20, rest: 45, cues: ["Hinge, full stretch, full squeeze"], subs: ["Standing Calf Raise"], note: "Loaded stretch on the gastroc."),
        .make("Single-Leg Calf Raise", .isolation, .bodyweight, primary: [.calves], mechanic: .isolation, unilateral: true, repLow: 12, repHigh: 20, rest: 45, cues: ["On a step, pause at the top"], subs: ["Standing Calf Raise"], note: "Anywhere calf work."),
        .make("Leg Press Calf Raise", .isolation, .machine, primary: [.calves], mechanic: .isolation, repLow: 12, repHigh: 20, rest: 45, cues: ["Balls of the feet on the sled", "Don't unlock the knees wildly"], subs: ["Standing Calf Raise"], note: "Heavy calves on the press."),
        .make("Tibialis Raise", .isolation, .bodyweight, primary: [.calves], mechanic: .isolation, repLow: 15, repHigh: 25, rest: 30, met: 3.0, cues: ["Heels planted, lift the toes"], subs: ["Seated Calf Raise"], note: "Shin strength for knees and running."),
        .make("Walking Calf Raise", .gait, .dumbbell, primary: [.calves], mechanic: .isolation, repLow: 20, repHigh: 40, rest: 45, cues: ["Rise onto the toes each step"], subs: ["Standing Calf Raise"], note: "Locomotor calves."),
    ]

    // ── Core + carries ──────────────────────────────────────────────
    static let expansionCore: [ExerciseDefinition] = [
        .make("Plate Pinch Hold", .carry, .bodyweight, primary: [.forearms], force: .isometric, repLow: 20, repHigh: 40, rest: 45, met: 3.5, cues: ["Pinch two plates, thumb and fingers"], subs: ["Farmer's Carry"], note: "Thumb-and-finger strength. Reps = seconds."),
        .make("Copenhagen Plank", .antiRotation, .bodyweight, primary: [.adductors], secondary: [.obliques], force: .isometric, level: .advanced, unilateral: true, repLow: 20, repHigh: 40, rest: 60, cues: ["Top foot on a bench", "Hips high"], pain: ["Knee"], subs: ["Hip Adduction"], note: "Adductor gold. Reps = seconds."),
        .make("Hanging Knee Raise", .coreFlexion, .bodyweight, primary: [.abs, .hipFlexors], force: .pull, rest: 45, cues: ["Posterior tilt, knees up without swing"], subs: ["Hanging Leg Raise"], note: "The hanging raise most people actually own."),
        .make("Toes-to-Bar", .coreFlexion, .bodyweight, primary: [.abs, .hipFlexors], secondary: [.lats], force: .pull, level: .advanced, rest: 60, cues: ["Pike, tap the bar, control the descent"], subs: ["Hanging Leg Raise"], note: "Gymnastic flexion under a bar."),
        .make("V-Up", .coreFlexion, .bodyweight, primary: [.abs], secondary: [.hipFlexors], rest: 45, cues: ["Hands and feet meet, lower slow"], subs: ["Hollow Hold"], note: "Full-body flexion."),
        .make("Bicycle Crunch", .rotation, .bodyweight, primary: [.obliques, .abs], rest: 45, cues: ["Slow elbow to opposite knee"], subs: ["Russian Twist"], note: "Rotational crunch that isn't frantic."),
        .make("Cable Woodchop", .rotation, .cable, primary: [.obliques], secondary: [.abs], rest: 45, cues: ["Rotate from the ribs, hips quiet"], subs: ["Russian Twist"], note: "High-to-low rotation under load."),
        .make("Landmine Rotation", .rotation, .barbell, primary: [.obliques], secondary: [.abs], rest: 45, cues: ["Arc the bar side to side, pivot the back foot"], subs: ["Cable Woodchop"], note: "Standing rotational power."),
        .make("Dragon Flag", .antiRotation, .bodyweight, primary: [.abs], secondary: [.obliques], force: .isometric, level: .advanced, rest: 75, cues: ["Hollow, lower as a plank from the shoulders"], pain: ["Lower Back"], subs: ["Ab Wheel Rollout"], note: "Elite anti-extension."),
        .make("L-Sit", .coreFlexion, .bodyweight, primary: [.abs, .hipFlexors], secondary: [.triceps], force: .isometric, level: .advanced, repLow: 10, repHigh: 20, rest: 45, cues: ["Lock the arms, lift the legs to horizontal"], subs: ["Hollow Hold"], note: "Gymnastic compression. Reps = seconds."),
        .make("Stir the Pot", .antiRotation, .bodyweight, primary: [.abs], secondary: [.obliques], force: .isometric, rest: 45, cues: ["Forearms on a ball, small circles, hips still"], subs: ["Plank"], note: "Plank with a moving base."),
        .make("Body Saw", .antiRotation, .bodyweight, primary: [.abs], secondary: [.obliques], force: .isometric, rest: 45, cues: ["Plank on sliders, rock long without sagging"], pain: ["Lower Back"], subs: ["Plank"], note: "Moving anti-extension."),
        .make("Plank Shoulder Tap", .antiRotation, .bodyweight, primary: [.abs, .obliques], secondary: [.frontDelts], force: .isometric, rest: 45, cues: ["Feet wide, tap without rocking"], subs: ["Plank"], note: "Anti-rotation plank."),
        .make("Hanging Windshield Wiper", .rotation, .bodyweight, primary: [.obliques], secondary: [.abs, .lats], level: .advanced, rest: 60, cues: ["Pike to vertical, sweep the legs side to side"], pain: ["Lower Back"], subs: ["Russian Twist"], note: "High-skill rotational hang."),
    ]

    // ── Conditioning ──────────────────────────────────────────────
    static let expansionConditioning: [ExerciseDefinition] = [
        .make("Suitcase Carry", .carry, .dumbbell, primary: [.obliques, .forearms], secondary: [.abs], force: .isometric, modality: .conditioning, repLow: 30, repHigh: 50, rest: 75, met: 6.0, cues: ["One side loaded, don't lean"], subs: ["Farmer's Carry"], note: "Anti-lateral-flexion walk. Reps = meters."),
        .make("Overhead Carry", .carry, .dumbbell, primary: [.frontDelts, .abs], secondary: [.forearms], force: .isometric, modality: .conditioning, repLow: 20, repHigh: 40, rest: 75, met: 6.0, cues: ["Lock the arm, ribs down"], pain: ["Shoulder"], subs: ["Farmer's Carry"], note: "Overhead stability on the move. Reps = meters."),
        .make("Front Rack Carry", .carry, .kettlebell, primary: [.abs, .upperBack], secondary: [.glutes], force: .isometric, modality: .conditioning, repLow: 20, repHigh: 40, rest: 75, met: 6.0, cues: ["Elbows up, breathe into the bells"], subs: ["Farmer's Carry"], note: "Clean-rack walk. Reps = meters."),
        .make("Waiter's Carry", .carry, .dumbbell, primary: [.frontDelts, .abs], secondary: [.forearms], force: .isometric, modality: .conditioning, unilateral: true, repLow: 20, repHigh: 40, rest: 60, met: 5.5, cues: ["One arm overhead like a tray"], pain: ["Shoulder"], subs: ["Overhead Carry"], note: "Single-arm overhead walk. Reps = meters."),
        .make("Ski Erg", .gait, .cardioMachine, primary: [.fullBody], secondary: [.lats, .cardio], force: .pull, modality: .conditioning, repLow: 250, repHigh: 1000, rest: 60, met: 9.0, cues: ["Hinge and pull, don't just yank the arms"], subs: ["Rowing Erg"], note: "Upper-body cardio. Reps = meters."),
        .make("Echo Bike", .gait, .cardioMachine, primary: [.fullBody], secondary: [.cardio], modality: .conditioning, repLow: 20, repHigh: 60, met: 10.0, cues: ["Push and pull the arms", "Pace the intervals"], subs: ["Assault Bike"], note: "Fan-bike intervals. Reps = seconds."),
        .make("Sled Drag", .carry, .sled, primary: [.hamstrings, .glutes], secondary: [.cardio], modality: .conditioning, repLow: 15, repHigh: 40, met: 8.0, cues: ["Lean back, short steps"], subs: ["Sled Push"], note: "Posterior-chain sled. Reps = meters."),
        .make("Sled Pull", .carry, .sled, primary: [.lats, .upperBack], secondary: [.cardio, .hamstrings], force: .pull, modality: .conditioning, repLow: 15, repHigh: 40, met: 8.0, cues: ["Hand-over-hand or backward walk"], subs: ["Sled Push"], note: "Upper-body sled. Reps = meters."),
        .make("Bear Crawl", .gait, .bodyweight, primary: [.fullBody], secondary: [.abs, .cardio], modality: .conditioning, repLow: 20, repHigh: 40, rest: 45, met: 7.0, cues: ["Knees hover, opposite limbs"], subs: ["Mountain Climbers"], note: "Locomotor core. Reps = meters."),
        .make("Devil Press", .hinge, .dumbbell, primary: [.fullBody], secondary: [.cardio], modality: .conditioning, level: .advanced, met: 9.5, cues: ["Burpee, then snatch both bells"], pain: ["Shoulder", "Lower Back"], subs: ["Burpee"], note: "Ugly, honest conditioning."),
        .make("Incline Treadmill Walk", .gait, .cardioMachine, primary: [.glutes, .cardio], secondary: [.calves], modality: .endurance, repLow: 600, repHigh: 1800, rest: 0, met: 6.5, cues: ["Steep grade, no hands on the rails"], subs: ["Stair Climber"], note: "Low-skill aerobic base. Reps = seconds."),
        .make("Double-Under", .gait, .cardioMachine, primary: [.calves], secondary: [.cardio], modality: .conditioning, level: .intermediate, repLow: 20, repHigh: 50, rest: 45, met: 12.0, cues: ["One jump, two rope turns"], subs: ["Jump Rope"], note: "Jump-rope skill work."),
        .make("High Knees", .gait, .bodyweight, primary: [.hipFlexors, .cardio], secondary: [.abs], modality: .conditioning, repLow: 20, repHigh: 40, rest: 30, met: 8.0, cues: ["Tall posture, quick ground contacts"], subs: ["Mountain Climbers"], note: "Warm-up or finisher. Reps = seconds."),
        .make("Bike Erg", .gait, .cardioMachine, primary: [.quads, .cardio], secondary: [.hamstrings], modality: .endurance, repLow: 600, repHigh: 1800, rest: 0, met: 7.5, cues: ["Smooth circles, don't mash"], subs: ["Assault Bike"], note: "Seated bike cardio. Reps = seconds."),
        .make("Elliptical", .gait, .cardioMachine, primary: [.cardio], secondary: [.quads, .glutes], modality: .endurance, repLow: 600, repHigh: 1800, rest: 0, met: 6.0, cues: ["Push and pull the handles, quiet feet"], subs: ["Treadmill Run"], note: "Low-impact aerobic. Reps = seconds."),
    ]

    // ── Mobility ──────────────────────────────────────────────
    static let expansionMobility: [ExerciseDefinition] = [
        .make("Scarecrow External Rotation", .isolation, .bands, primary: [.rearDelts], secondary: [.upperBack], mechanic: .isolation, force: .pull, modality: .mobility, rest: 30, cues: ["Elbows high, rotate the hands back"], subs: ["Face Pull"], note: "Warm-up for the rotator cuff."),
        .make("McGill Curl-Up", .coreFlexion, .bodyweight, primary: [.abs], force: .isometric, modality: .mobility, rest: 30, cues: ["One knee bent, lift the head and shoulders an inch"], subs: ["Dead Bug"], note: "Spine-sparing ab brace."),
        .make("Pigeon Stretch", .mobility, .bodyweight, primary: [.glutes], secondary: [.hipFlexors], force: .isometric, modality: .mobility, unilateral: true, repLow: 30, repHigh: 45, rest: 20, met: 2.5, cues: ["Square the hips, breathe into the back hip"], note: "Glute and hip-rotator length. Reps = seconds."),
        .make("Figure-4 Stretch", .mobility, .bodyweight, primary: [.glutes], force: .isometric, modality: .mobility, unilateral: true, repLow: 30, repHigh: 45, rest: 20, met: 2.5, cues: ["Ankle on the opposite knee, pull the thigh in"], note: "Supine piriformis. Reps = seconds."),
        .make("Thread the Needle", .mobility, .bodyweight, primary: [.upperBack], force: .isometric, modality: .mobility, unilateral: true, repLow: 6, repHigh: 10, rest: 20, met: 2.5, cues: ["Reach the arm under, rest the shoulder"], note: "Thoracic rotation on all fours."),
        .make("Wall Slide", .mobility, .bodyweight, primary: [.upperBack], secondary: [.rearDelts], force: .isometric, modality: .mobility, rest: 20, met: 2.5, cues: ["Back to the wall, slide the arms without arching"], note: "Overhead-position prep."),
        .make("Spiderman Lunge", .mobility, .bodyweight, primary: [.hipFlexors], secondary: [.adductors], force: .isometric, modality: .mobility, unilateral: true, rest: 20, cues: ["Long lunge, inside elbow down", "Keep the back knee soft"], note: "Hip opener that isn't a static hold."),
        .make("Open Book", .mobility, .bodyweight, primary: [.upperBack], force: .isometric, modality: .mobility, unilateral: true, rest: 20, cues: ["Knees stacked, open the top arm and follow it"], note: "Ribcage rotation."),
        .make("Pec Doorway Stretch", .mobility, .bodyweight, primary: [.chest, .frontDelts], force: .isometric, modality: .mobility, unilateral: true, repLow: 30, repHigh: 45, rest: 20, met: 2.5, cues: ["Forearm on the jamb, step through"], note: "Counter to pressing. Reps = seconds."),
        .make("Lat Hang Stretch", .mobility, .bodyweight, primary: [.lats], secondary: [.chest], force: .isometric, modality: .mobility, repLow: 20, repHigh: 40, rest: 20, met: 2.5, cues: ["Dead hang, ribcage down, breathe"], note: "Decompress the shoulders. Reps = seconds."),
        .make("Hip CARs", .mobility, .bodyweight, primary: [.hipFlexors], secondary: [.glutes], force: .isometric, modality: .mobility, unilateral: true, repLow: 4, repHigh: 6, rest: 20, met: 2.5, cues: ["Biggest pain-free circle, torso still"], note: "Controlled articular rotations for the hip."),
        .make("Ankle CARs", .mobility, .bodyweight, primary: [.calves], force: .isometric, modality: .mobility, unilateral: true, repLow: 6, repHigh: 8, rest: 20, met: 2.0, cues: ["Slow circles, don't fake it at the knee"], note: "Ankle range for squats and running."),
        .make("Child's Pose", .mobility, .bodyweight, primary: [.lats, .lowerBack], force: .isometric, modality: .mobility, repLow: 30, repHigh: 60, rest: 20, met: 2.0, cues: ["Hips to heels, arms long, breathe wide"], note: "Down-regulation. Reps = seconds."),
        .make("Downward Dog", .mobility, .bodyweight, primary: [.hamstrings, .calves], secondary: [.upperBack], force: .isometric, modality: .mobility, repLow: 20, repHigh: 40, rest: 20, met: 3.0, cues: ["Push the floor away, heels toward the ground"], note: "Posterior-chain plus shoulders. Reps = seconds."),
        .make("Bretzel Stretch", .mobility, .bodyweight, primary: [.hipFlexors, .upperBack], secondary: [.quads], force: .isometric, modality: .mobility, unilateral: true, repLow: 30, repHigh: 45, rest: 20, met: 2.5, cues: ["Bottom leg bent, twist and breathe"], note: "Hip plus T-spine. Reps = seconds."),
        .make("Frog Stretch", .mobility, .bodyweight, primary: [.adductors], secondary: [.hipFlexors], force: .isometric, modality: .mobility, repLow: 30, repHigh: 45, rest: 20, met: 2.5, cues: ["Knees wide, sit the hips back"], pain: ["Knee"], note: "Adductor length. Reps = seconds."),
        .make("Chin Tucks", .mobility, .bodyweight, primary: [.upperBack], force: .isometric, modality: .mobility, rest: 15, met: 1.5, cues: ["Make a double chin, long neck"], note: "Deep-neck flexors for desk posture."),
        .make("Scapular Push-Up", .mobility, .bodyweight, primary: [.upperBack], secondary: [.chest], force: .isometric, modality: .mobility, rest: 20, cues: ["Lock the elbows, shrug the shoulder blades apart and together"], note: "Serratus and scapular control."),
    ]

    // ── Kettlebell, bands, suspension ──────────────────────────────────────────────
    static let expansionTools: [ExerciseDefinition] = [
        .make("Turkish Get-Up", .mobility, .kettlebell, primary: [.fullBody], secondary: [.abs, .frontDelts, .glutes], level: .intermediate, unilateral: true, repLow: 3, repHigh: 5, met: 5.5, cues: ["Eyes on the bell", "Slow, one position at a time"], pain: ["Shoulder", "Wrist"], subs: ["Overhead Press"], note: "Get-up as a loaded mobility skill."),
        .make("Kettlebell Windmill", .mobility, .kettlebell, primary: [.obliques], secondary: [.hamstrings, .frontDelts], level: .intermediate, unilateral: true, rest: 60, cues: ["Bell overhead, hinge and rotate to the floor"], pain: ["Shoulder", "Lower Back"], subs: ["Kettlebell Swing"], note: "Oblique plus overhead stability."),
        .make("Kettlebell Front Squat", .squat, .kettlebell, primary: [.quads, .glutes], secondary: [.abs], cues: ["Elbows up, bells in the rack"], pain: ["Knee"], subs: ["Goblet Squat"], note: "Double-rack squat."),
        .make("Kettlebell Halo", .mobility, .kettlebell, primary: [.frontDelts], secondary: [.upperBack], force: .isometric, modality: .mobility, rest: 30, cues: ["Circle the bell around the head, ribs down"], pain: ["Shoulder"], subs: ["Shoulder Dislocates"], note: "Shoulder CARs with a bell."),
        .make("TRX Push-Up", .horizontalPush, .trx, primary: [.chest], secondary: [.abs, .triceps], rest: 60, cues: ["Feet or hands in the straps", "Body as a plank"], subs: ["Push-Up"], note: "Suspension push-up."),
        .make("TRX Hamstring Curl", .isolation, .trx, primary: [.hamstrings], secondary: [.glutes], mechanic: .isolation, force: .pull, rest: 60, cues: ["Heels in the straps, curl in, hips high"], subs: ["Lying Leg Curl"], note: "Hamstring curl without a machine."),
        .make("TRX Pike", .coreFlexion, .trx, primary: [.abs], secondary: [.hipFlexors], rest: 45, cues: ["Feet in straps, pike the hips over the shoulders"], pain: ["Lower Back"], subs: ["Mountain Climbers"], note: "Suspension pike for the abs."),
        .make("Lateral Band Walk", .gait, .bands, primary: [.abductors, .glutes], mechanic: .isolation, repLow: 12, repHigh: 20, rest: 30, met: 3.5, cues: ["Band at the knees, stay in a half squat"], subs: ["Hip Abduction"], note: "Glute medius that actually shows up in gait."),
        .make("Monster Walk", .gait, .bands, primary: [.abductors, .glutes], mechanic: .isolation, repLow: 12, repHigh: 20, rest: 30, met: 3.5, cues: ["Band at the ankles, wide athletic steps"], subs: ["Lateral Band Walk"], note: "Forward and back band gait."),
        .make("Banded Glute Bridge", .hinge, .bands, primary: [.glutes], secondary: [.hamstrings], rest: 45, cues: ["Band above the knees, drive out and up"], subs: ["Glute Bridge"], note: "Bridge with lateral tension."),
        .make("Band Good Morning", .hinge, .bands, primary: [.hamstrings, .lowerBack], secondary: [.glutes], force: .pull, rest: 45, cues: ["Band under the feet, hinge with a flat back"], pain: ["Lower Back"], subs: ["Good Morning"], note: "Hinge pattern with a band."),
        .make("TRX Face Pull", .horizontalPull, .trx, primary: [.rearDelts], secondary: [.upperBack], mechanic: .isolation, force: .pull, rest: 45, cues: ["Pull to the eyes, externally rotate"], subs: ["Face Pull"], note: "Suspension face pull."),
        .make("TRX Lunge", .lunge, .trx, primary: [.quads, .glutes], secondary: [.hamstrings], unilateral: true, rest: 60, cues: ["Back foot in the strap, drop and drive"], pain: ["Knee"], subs: ["Bulgarian Split Squat"], note: "Rear-foot-elevated on straps."),
        .make("Kettlebell Clean", .hinge, .kettlebell, primary: [.glutes, .traps], secondary: [.forearms], force: .pull, modality: .power, unilateral: true, rest: 60, cues: ["Hike, zip the coat, catch in the rack"], pain: ["Wrist"], subs: ["Kettlebell Swing"], note: "The rack you need for front squats."),
    ]

    // ── Dedicated calisthenics skills ──────────────────────────────────────────────
    static let expansionCalisthenics: [ExerciseDefinition] = [
        .make("Pike Push-Up", .verticalPush, .bodyweight, primary: [.frontDelts], secondary: [.triceps, .abs], level: .intermediate, rest: 75, cues: ["Hips high, head toward the floor", "Elbows in, press the floor away"], faults: ["Collapsing the pike", "Flaring the elbows"], pain: ["Shoulder", "Wrist"], regress: ["Incline Push-Up"], progress: ["Handstand Push-Up"], subs: ["Seated Dumbbell Shoulder Press"], note: "The overhead press you already own."),
        .make("Handstand Push-Up", .verticalPush, .bodyweight, primary: [.frontDelts], secondary: [.triceps, .abs], level: .advanced, rest: 120, cues: ["Kick to the wall, hollow body", "Head to the floor, press to lockout"], faults: ["Banana back", "Head too far from the wall"], pain: ["Shoulder", "Wrist", "Neck"], regress: ["Pike Push-Up"], progress: ["Wall Walk"], subs: ["Pike Push-Up"], note: "Inverted pressing skill."),
        .make("Wall Handstand Push-Up", .verticalPush, .bodyweight, primary: [.frontDelts], secondary: [.triceps], level: .advanced, rest: 120, cues: ["Belly to the wall if you have it", "Short range, full lockout"], pain: ["Shoulder", "Wrist"], regress: ["Pike Push-Up"], subs: ["Handstand Push-Up"], note: "The honest HSPU with a wall."),
        .make("Archer Push-Up", .horizontalPush, .bodyweight, primary: [.chest], secondary: [.triceps, .abs], level: .advanced, unilateral: true, rest: 75, cues: ["Shift over one arm, other arm long", "Chest between the working hand"], faults: ["Hips twisting"], pain: ["Shoulder", "Wrist"], regress: ["Push-Up"], progress: ["One-Arm Push-Up"], subs: ["Decline Push-Up"], note: "Unilateral push-up toward a one-arm."),
        .make("Pseudo Planche Push-Up", .horizontalPush, .bodyweight, primary: [.frontDelts, .chest], secondary: [.triceps, .abs], level: .advanced, rest: 90, cues: ["Hands by the ribs, lean forward", "Lock the elbows, hollow the body"], faults: ["Hips sagging", "Hands too far forward without the lean"], pain: ["Wrist", "Shoulder"], regress: ["Planche Lean"], progress: ["Tuck Planche"], subs: ["Push-Up"], note: "Planche strength inside a push-up."),
        .make("Clap Push-Up", .horizontalPush, .bodyweight, primary: [.chest], secondary: [.triceps, .abs], modality: .power, level: .intermediate, rest: 75, cues: ["Explode, clap, land soft", "Stay a plank in the air"], faults: ["Worming off the floor"], pain: ["Wrist", "Shoulder"], regress: ["Push-Up"], subs: ["Push-Up"], note: "Plyometric push-up."),
        .make("Hindu Push-Up", .horizontalPush, .bodyweight, primary: [.chest, .frontDelts], secondary: [.triceps, .abs], level: .intermediate, rest: 60, cues: ["Dive to a low plank, scoop to upward dog", "Hips lead the way back"], pain: ["Shoulder", "Wrist"], regress: ["Push-Up"], subs: ["Push-Up"], note: "The flowing dive-bomber."),
        .make("Knee Push-Up", .horizontalPush, .bodyweight, primary: [.chest], secondary: [.triceps], level: .beginner, rest: 45, cues: ["Knees down, body still a line from head to knee", "Full lockout"], faults: ["Hips collapsing"], regress: ["Incline Push-Up"], progress: ["Push-Up"], subs: ["Incline Push-Up"], note: "The honest first push-up."),
        .make("Muscle-Up", .verticalPull, .bodyweight, primary: [.lats, .triceps], secondary: [.chest, .abs], force: .pull, level: .advanced, rest: 150, cues: ["False grip if on rings", "Pull high, then sit through"], faults: ["Kipping before you can pull"], pain: ["Shoulder", "Wrist", "Elbow"], regress: ["Chest-to-Bar Pull-Up"], progress: ["Weighted Pull-Up"], subs: ["Pull-Up"], note: "Pull that becomes a dip."),
        .make("Typewriter Pull-Up", .verticalPull, .bodyweight, primary: [.lats], secondary: [.biceps, .upperBack], force: .pull, level: .advanced, rest: 120, cues: ["Chin over, shift side to side", "Don't drop the height"], pain: ["Shoulder", "Elbow"], regress: ["Pull-Up"], subs: ["Wide-Grip Pull-Up"], note: "Lat width with a traveling chin."),
        .make("Archer Pull-Up", .verticalPull, .bodyweight, primary: [.lats], secondary: [.biceps], force: .pull, level: .advanced, unilateral: true, rest: 120, cues: ["Pull to one side, other arm long", "Chest to the working hand"], pain: ["Shoulder", "Elbow"], regress: ["Pull-Up"], progress: ["One-Arm Pull-Up"], subs: ["Pull-Up"], note: "Unilateral pull toward a one-arm."),
        .make("Commando Pull-Up", .verticalPull, .bodyweight, primary: [.lats, .biceps], secondary: [.abs], force: .pull, level: .intermediate, rest: 90, cues: ["Straddle the bar, alternate sides of the head", "Don't swing"], pain: ["Shoulder"], regress: ["Chin-Up"], subs: ["Chin-Up"], note: "Along-the-bar pull-up."),
        .make("Skin the Cat", .verticalPull, .bodyweight, primary: [.lats, .abs], secondary: [.frontDelts], force: .pull, level: .advanced, rest: 90, cues: ["From a hang, pike through to inverted", "Control the German hang"], pain: ["Shoulder"], regress: ["Dead Hang"], subs: ["Hanging Leg Raise"], note: "Shoulder mobility plus compression. Go slow."),
        .make("Jumping Pull-Up", .verticalPull, .bodyweight, primary: [.lats], secondary: [.biceps], force: .pull, rest: 60, cues: ["Jump to the bar, lower slow", "Chin over if you can"], progress: ["Negative Pull-Up"], subs: ["Assisted Pull-Up"], note: "The path to a first pull-up."),
        .make("Negative Pull-Up", .verticalPull, .bodyweight, primary: [.lats], secondary: [.biceps], force: .pull, level: .intermediate, rest: 90, cues: ["Jump or step to the top", "Lower for three to five seconds"], progress: ["Pull-Up"], subs: ["Jumping Pull-Up"], note: "Eccentric pull-up strength."),
        .make("Chest-to-Bar Pull-Up", .verticalPull, .bodyweight, primary: [.lats, .upperBack], secondary: [.biceps], force: .pull, level: .advanced, rest: 120, cues: ["Pull until the chest kisses the bar", "Don't kip unless that's the point"], pain: ["Shoulder"], regress: ["Pull-Up"], progress: ["Muscle-Up"], subs: ["Pull-Up"], note: "The pull-up that actually finishes."),
        .make("Shrimp Squat", .squat, .bodyweight, primary: [.quads, .glutes], secondary: [.abs], level: .advanced, unilateral: true, rest: 90, cues: ["Hold the back foot, sit the knee toward the floor", "Stand without touching the knee if you can"], faults: ["Falling to the side"], pain: ["Knee"], regress: ["Air Squat"], progress: ["Pistol Squat"], subs: ["Pistol Squat"], note: "Rear-foot-held single-leg squat."),
        .make("Air Squat", .squat, .bodyweight, primary: [.quads, .glutes], secondary: [.hamstrings], rest: 45, cues: ["Sit between the hips, chest up", "Heels stay down"], faults: ["Knees caving", "Heels lifting"], progress: ["Pistol Squat"], subs: ["Goblet Squat"], note: "The squat you can do in a living room."),
        .make("Wall Sit", .squat, .bodyweight, primary: [.quads], secondary: [.glutes], force: .isometric, rest: 45, repLow: 30, repHigh: 60, cues: ["Back on the wall, thighs parallel", "Breathe, don't rest on the knees"], pain: ["Knee"], subs: ["Air Squat"], note: "Isometric quads. Reps = seconds."),
        .make("Tuck Planche", .antiRotation, .bodyweight, primary: [.frontDelts, .abs], secondary: [.triceps], force: .isometric, level: .advanced, rest: 75, repLow: 8, repHigh: 20, cues: ["Lean, lock the elbows, tuck the knees", "Protract the shoulders"], faults: ["Bent elbows", "Hips dropping"], pain: ["Wrist", "Shoulder"], regress: ["Planche Lean"], progress: ["Advanced Tuck Planche"], subs: ["Pseudo Planche Push-Up"], note: "The first real planche shape. Reps = seconds."),
        .make("Frog Stand", .antiRotation, .bodyweight, primary: [.frontDelts], secondary: [.abs, .triceps], force: .isometric, level: .intermediate, rest: 45, repLow: 10, repHigh: 30, cues: ["Knees on the triceps, lean until the feet lift", "Look forward"], pain: ["Wrist"], progress: ["Tuck Planche"], subs: ["Crow Pose"], note: "Balance gate to planche. Reps = seconds."),
        .make("Handstand Hold", .verticalPush, .bodyweight, primary: [.frontDelts], secondary: [.abs, .triceps], force: .isometric, level: .intermediate, rest: 60, repLow: 15, repHigh: 40, cues: ["Hollow, squeeze the glutes", "Fingertips do the balancing"], faults: ["Banana back"], pain: ["Wrist", "Shoulder"], regress: ["Wall Walk"], progress: ["Handstand Push-Up"], subs: ["Pike Push-Up"], note: "Inverted balance. Reps = seconds."),
        .make("Front Lever Tuck", .horizontalPull, .bodyweight, primary: [.lats, .abs], secondary: [.upperBack], force: .isometric, level: .advanced, rest: 75, repLow: 8, repHigh: 20, cues: ["From a hang, tuck and lift to horizontal", "Depress the shoulders"], pain: ["Shoulder"], regress: ["Hanging Knee Raise"], progress: ["Front Lever"], subs: ["Hanging Leg Raise"], note: "The first front-lever shape. Reps = seconds."),
        .make("Back Lever Tuck", .horizontalPull, .bodyweight, primary: [.lats, .abs], secondary: [.frontDelts], force: .isometric, level: .advanced, rest: 75, repLow: 8, repHigh: 20, cues: ["Skin the cat into a tuck, body long later", "Stay hollow"], pain: ["Shoulder"], regress: ["Skin the Cat"], subs: ["Skin the Cat"], note: "Posterior lever intro. Reps = seconds."),
        .make("Hollow Rock", .coreFlexion, .bodyweight, primary: [.abs], force: .isometric, rest: 45, cues: ["Hollow hold, then small rocks", "Low back stays glued"], faults: ["Opening the hollow"], subs: ["Hollow Hold"], note: "Moving hollow-body."),
        .make("Superman Hold", .hinge, .bodyweight, primary: [.lowerBack, .glutes], secondary: [.upperBack], force: .isometric, rest: 45, repLow: 20, repHigh: 40, cues: ["Lift chest and legs, squeeze the glutes", "Don't crank the neck"], subs: ["Back Extension"], note: "Posterior-chain hold. Reps = seconds."),
        .make("Sit-Up", .coreFlexion, .bodyweight, primary: [.abs], secondary: [.hipFlexors], rest: 45, cues: ["Feet anchored or not — pick one and own it", "Sit all the way up"], faults: ["Yanking the neck"], subs: ["Hollow Hold"], note: "The classic flexion."),
        .make("Flutter Kick", .coreFlexion, .bodyweight, primary: [.abs, .hipFlexors], rest: 30, repLow: 20, repHigh: 40, cues: ["Hollow, small kicks, low back down"], pain: ["Lower Back"], subs: ["Hollow Hold"], note: "Hip-flexor plus hollow. Reps = per side."),
        .make("Planche Lean", .antiRotation, .bodyweight, primary: [.frontDelts, .abs], secondary: [.triceps], force: .isometric, level: .intermediate, rest: 45, repLow: 15, repHigh: 30, cues: ["Hands under the hips, lean until the toes get light", "Lock the elbows"], pain: ["Wrist"], progress: ["Tuck Planche"], subs: ["Pseudo Planche Push-Up"], note: "The lean that teaches planche. Reps = seconds."),
        .make("Wall Walk", .verticalPush, .bodyweight, primary: [.frontDelts, .abs], secondary: [.triceps], level: .intermediate, rest: 90, cues: ["From a plank, walk the feet up the wall", "Hands walk in, stay hollow"], faults: ["Dumping the lumbar"], pain: ["Wrist", "Shoulder"], regress: ["Pike Push-Up"], progress: ["Handstand Hold"], subs: ["Pike Push-Up"], note: "The path to a freestanding handstand."),
        .make("Straight-Bar Dip", .horizontalPush, .bodyweight, primary: [.chest, .triceps], secondary: [.frontDelts], level: .intermediate, rest: 90, cues: ["Bar behind you, lean slightly", "Shoulders down, full lockout"], pain: ["Shoulder", "Wrist"], regress: ["Bench Dip"], progress: ["Muscle-Up"], subs: ["Chest Dip"], note: "The dip that follows a bar muscle-up."),
        .make("Crow Pose", .antiRotation, .bodyweight, primary: [.frontDelts, .abs], secondary: [.triceps], force: .isometric, level: .intermediate, rest: 45, repLow: 10, repHigh: 30, cues: ["Knees high on the arms, gaze forward", "Bend the elbows to a shelf"], pain: ["Wrist"], progress: ["Frog Stand"], subs: ["Frog Stand"], note: "Yoga gate to arm-balance. Reps = seconds."),
        .make("Dead Hang", .verticalPull, .bodyweight, primary: [.forearms, .lats], force: .isometric, rest: 45, repLow: 20, repHigh: 45, cues: ["Shoulders packed, ribs down", "Breathe"], pain: ["Shoulder"], progress: ["Pull-Up"], subs: ["Lat Hang Stretch"], note: "Grip and shoulder health. Reps = seconds."),
        .make("Scapular Pull-Up", .verticalPull, .bodyweight, primary: [.lats, .upperBack], force: .pull, rest: 45, cues: ["From a dead hang, depress the scaps without bending the elbows"], progress: ["Pull-Up"], subs: ["Dead Hang"], note: "The first inch of a pull-up."),
    ]

    // ── Sports ARIA can log as training ──────────────────────────────────────────────
    static let expansionSports: [ExerciseDefinition] = [
        .make("Basketball", .gait, .sport, primary: [.cardio, .fullBody], secondary: [.calves, .abs], modality: .sport, rest: 0, met: 8.0, cues: ["Play the game you actually play", "I log the minutes, not the box score"], note: "Tell ARIA you played — it counts as training."),
        .make("Soccer", .gait, .sport, primary: [.cardio, .fullBody], secondary: [.quads, .calves], modality: .sport, rest: 0, met: 9.0, cues: ["Minutes on the pitch are the session", "Hydrate like you mean it after"], note: "Field sport. Log it when you play."),
        .make("Tennis", .gait, .sport, primary: [.cardio], secondary: [.frontDelts, .obliques], modality: .sport, rest: 0, met: 7.5, cues: ["Sets and matches are volume", "Shoulders and hips both work"], note: "Court sport. Log a match as a session."),
        .make("Volleyball", .gait, .sport, primary: [.cardio], secondary: [.frontDelts, .calves], modality: .sport, rest: 0, met: 6.5, cues: ["Jumps and hits add up", "Land quiet"], pain: ["Shoulder", "Knee"], note: "Court sport with a jump tax."),
        .make("Baseball", .gait, .sport, primary: [.cardio], secondary: [.obliques, .frontDelts], modality: .sport, rest: 0, met: 5.0, cues: ["Warm the throwing arm", "I still count the hours"], note: "Diamond time is training time."),
        .make("Softball", .gait, .sport, primary: [.cardio], secondary: [.obliques, .frontDelts], modality: .sport, rest: 0, met: 5.0, cues: ["Throw warm, hips first"], note: "Same as baseball — log the game."),
        .make("Golf", .gait, .sport, primary: [.obliques], secondary: [.cardio, .glutes], modality: .sport, rest: 0, met: 4.5, cues: ["Walk the course if you can", "Rotation is the work"], note: "Walking golf is real volume."),
        .make("Pickleball", .gait, .sport, primary: [.cardio], secondary: [.frontDelts, .calves], modality: .sport, rest: 0, met: 6.0, cues: ["Short court, honest heart rate"], note: "The sport people actually keep doing."),
        .make("Badminton", .gait, .sport, primary: [.cardio], secondary: [.frontDelts, .calves], modality: .sport, rest: 0, met: 7.0, cues: ["Lunges and overheads"], pain: ["Shoulder"], note: "Court speed work."),
        .make("Table Tennis", .gait, .sport, primary: [.cardio], secondary: [.forearms, .obliques], modality: .sport, rest: 0, met: 4.0, cues: ["Footwork is the session"], note: "Ping pong still counts."),
        .make("Hockey", .gait, .sport, primary: [.cardio, .fullBody], secondary: [.obliques, .glutes], modality: .sport, rest: 0, met: 8.0, cues: ["Shifts are intervals"], note: "Ice or street — log the minutes."),
        .make("Lacrosse", .gait, .sport, primary: [.cardio, .fullBody], secondary: [.frontDelts, .obliques], modality: .sport, rest: 0, met: 8.0, cues: ["Running plus the stick"], note: "Field sport. Log it."),
        .make("Rugby", .gait, .sport, primary: [.fullBody, .cardio], secondary: [.glutes, .abs], modality: .sport, rest: 0, met: 10.0, cues: ["Contact plus running", "Recover like it happened"], pain: ["Shoulder", "Neck"], note: "Hard minutes. Log the match."),
        .make("Football", .gait, .sport, primary: [.fullBody, .cardio], secondary: [.quads, .abs], modality: .sport, rest: 0, met: 8.0, cues: ["Practice and games both count"], note: "American football. Tell ARIA the minutes."),
        .make("Ultimate Frisbee", .gait, .sport, primary: [.cardio], secondary: [.quads, .calves], modality: .sport, rest: 0, met: 8.0, cues: ["Sprints and cuts"], pain: ["Knee", "Ankle"], note: "The running sport with a disc."),
        .make("Hiking", .gait, .sport, primary: [.glutes, .cardio], secondary: [.calves, .quads], modality: .sport, rest: 0, met: 6.0, cues: ["Hills are the load", "I log the time on trail"], note: "Trail time is training."),
        .make("Rock Climbing", .gait, .sport, primary: [.forearms, .lats], secondary: [.abs, .cardio], modality: .sport, rest: 0, met: 7.0, cues: ["Fingers and hips", "Rest between burns"], pain: ["Finger", "Shoulder"], note: "Gym or crag — log the session."),
        .make("Boxing", .gait, .sport, primary: [.cardio, .fullBody], secondary: [.frontDelts, .abs], modality: .sport, rest: 0, met: 9.0, cues: ["Rounds are the sets"], pain: ["Wrist", "Shoulder"], note: "Bag, pads, or sparring — log the rounds as minutes."),
        .make("Martial Arts", .gait, .sport, primary: [.fullBody, .cardio], secondary: [.abs, .obliques], modality: .sport, rest: 0, met: 8.0, cues: ["Class time is the session"], note: "BJJ, karate, muay thai — name it and I'll write it down."),
        .make("Skiing", .gait, .sport, primary: [.quads, .glutes], secondary: [.cardio, .abs], modality: .sport, rest: 0, met: 7.0, cues: ["Runs add up in the legs"], pain: ["Knee"], note: "A day on snow is a leg day."),
        .make("Snowboarding", .gait, .sport, primary: [.quads, .glutes], secondary: [.obliques, .cardio], modality: .sport, rest: 0, met: 6.5, cues: ["Edge work is isometric legs"], pain: ["Knee", "Ankle"], note: "Log the hours on snow."),
        .make("Surfing", .gait, .sport, primary: [.lats, .abs], secondary: [.cardio, .frontDelts], modality: .sport, rest: 0, met: 6.0, cues: ["Paddle is the volume"], pain: ["Shoulder"], note: "Water time counts."),
        .make("Skateboarding", .gait, .sport, primary: [.quads, .glutes], secondary: [.abs, .cardio], modality: .sport, rest: 0, met: 5.5, cues: ["Balance plus impact"], pain: ["Ankle", "Wrist"], note: "Session at the park is training."),
        .make("Dance", .gait, .sport, primary: [.cardio, .fullBody], secondary: [.glutes, .calves], modality: .sport, rest: 0, met: 6.5, cues: ["Class or a night out — minutes still count"], note: "Movement is training. I'll log it."),
    ]

}
