#!/usr/bin/env python3
"""Generate production client config from Terraform client_configuration output.

Usage:
  terraform output -json client_configuration > client-configuration.json
  python3 scripts/generate_client_config.py

Reads client-configuration.json (or --input) and writes:
  - clients/web/.env.production.local
  - ForgeSwift/Config/Forge-Production.xcconfig
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "client-configuration.json"
WEB_OUTPUT = ROOT / "clients" / "web" / ".env.production.local"
IOS_OUTPUT = ROOT / "ForgeSwift" / "Config" / "Forge-Production.xcconfig"

REQUIRED_TOP_LEVEL = ("apiBaseUrl", "cognito")
REQUIRED_COGNITO = ("region", "userPoolId", "webClientId", "iosClientId")


def _load_config(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise FileNotFoundError(
            f"Config not found: {path}\n"
            "Export Terraform output first:\n"
            "  terraform output -json client_configuration > client-configuration.json"
        )
    with path.open(encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, dict):
        raise ValueError("client configuration must be a JSON object")
    return data


def _require_keys(payload: dict[str, Any], keys: tuple[str, ...], label: str) -> None:
    missing = [key for key in keys if not payload.get(key)]
    if missing:
        joined = ", ".join(missing)
        raise ValueError(f"{label} is missing required field(s): {joined}")


def _validate_api_base_url(value: str) -> str:
    trimmed = value.strip()
    parsed = urlparse(trimmed)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise ValueError(f"apiBaseUrl must be an absolute http(s) URL, got: {value!r}")
    if parsed.hostname in {"127.0.0.1", "localhost"}:
        raise ValueError("apiBaseUrl must not point at localhost for production config")
    return trimmed.rstrip("/")


def validate_config(data: dict[str, Any]) -> dict[str, Any]:
    _require_keys(data, REQUIRED_TOP_LEVEL, "client configuration")

    api_base_url = _validate_api_base_url(str(data["apiBaseUrl"]))

    cognito = data.get("cognito")
    if not isinstance(cognito, dict):
        raise ValueError("cognito must be an object")
    _require_keys(cognito, REQUIRED_COGNITO, "cognito")

    return {
        "apiBaseUrl": api_base_url,
        "cognito": {
            "region": str(cognito["region"]).strip(),
            "userPoolId": str(cognito["userPoolId"]).strip(),
            "webClientId": str(cognito["webClientId"]).strip(),
            "iosClientId": str(cognito["iosClientId"]).strip(),
            "identityPoolId": str(cognito.get("identityPoolId", "")).strip(),
        },
        "storage": data.get("storage") if isinstance(data.get("storage"), dict) else {},
    }


def render_web_env(config: dict[str, Any]) -> str:
    cognito = config["cognito"]
    lines = [
        "# Generated by scripts/generate_client_config.py — do not edit by hand.",
        f"NEXT_PUBLIC_API_URL={config['apiBaseUrl']}",
        f"NEXT_PUBLIC_COGNITO_REGION={cognito['region']}",
        f"NEXT_PUBLIC_COGNITO_CLIENT_ID={cognito['webClientId']}",
        f"NEXT_PUBLIC_COGNITO_USER_POOL_ID={cognito['userPoolId']}",
    ]
    if cognito["identityPoolId"]:
        lines.append(f"NEXT_PUBLIC_COGNITO_IDENTITY_POOL_ID={cognito['identityPoolId']}")
    return "\n".join(lines) + "\n"


def render_ios_xcconfig(config: dict[str, Any]) -> str:
    cognito = config["cognito"]
    api_url = config["apiBaseUrl"].replace("/", r"\/")
    return "\n".join(
        [
            "// Generated by scripts/generate_client_config.py — do not edit by hand.",
            f"FORGE_API_BASE_URL = {api_url}",
            "FORGE_USE_AUTH = true",
            f"FORGE_COGNITO_REGION = {cognito['region']}",
            f"FORGE_COGNITO_CLIENT_ID = {cognito['iosClientId']}",
            "FORGE_WEB_CALLBACK_BASE_URL = forge:/\\/device-connected",
            "",
        ]
    )


def generate(
    input_path: Path,
    *,
    web_output: Path = WEB_OUTPUT,
    ios_output: Path = IOS_OUTPUT,
    write: bool = True,
) -> dict[str, str]:
    config = validate_config(_load_config(input_path))
    outputs = {
        "web": render_web_env(config),
        "ios": render_ios_xcconfig(config),
    }
    if write:
        web_output.parent.mkdir(parents=True, exist_ok=True)
        ios_output.parent.mkdir(parents=True, exist_ok=True)
        web_output.write_text(outputs["web"], encoding="utf-8")
        ios_output.write_text(outputs["ios"], encoding="utf-8")

        def _display_path(path: Path) -> str:
            try:
                return str(path.relative_to(ROOT))
            except ValueError:
                return str(path)

        print(f"Wrote {_display_path(web_output)}")
        print(f"Wrote {_display_path(ios_output)}")
    return outputs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=f"Path to client-configuration.json (default: {DEFAULT_INPUT})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate and print outputs without writing files",
    )
    args = parser.parse_args(argv)

    try:
        outputs = generate(args.input, write=not args.dry_run)
    except (FileNotFoundError, ValueError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.dry_run:
        for label, content in outputs.items():
            print(f"--- {label} ---")
            print(content, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())